// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package notify

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMaintenanceWindowInstance = `-- name: AddMaintenanceWindowInstance :exec
INSERT INTO maintenance_window_instance (maintenance_window_id, instance_id)
VALUES ($1, $2)
`

type AddMaintenanceWindowInstanceParams struct {
	MaintenanceWindowID pgtype.UUID
	InstanceID          pgtype.UUID
}

func (q *Queries) AddMaintenanceWindowInstance(ctx context.Context, arg AddMaintenanceWindowInstanceParams) error {
	_, err := q.db.Exec(ctx, addMaintenanceWindowInstance, arg.MaintenanceWindowID, arg.InstanceID)
	return err
}

const addNotificationContactGroupMember = `-- name: AddNotificationContactGroupMember :exec
INSERT INTO notification_contact_group_member (group_id, contact_id) VALUES ($1, $2)
`

type AddNotificationContactGroupMemberParams struct {
	GroupID   pgtype.UUID
	ContactID pgtype.UUID
}

func (q *Queries) AddNotificationContactGroupMember(ctx context.Context, arg AddNotificationContactGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addNotificationContactGroupMember, arg.GroupID, arg.ContactID)
	return err
}

const addNotificationPolicyChannel = `-- name: AddNotificationPolicyChannel :exec
INSERT INTO notification_policy_channel (policy_id, channel, channel_target_id) VALUES ($1, $2, $3)
`

type AddNotificationPolicyChannelParams struct {
	PolicyID        pgtype.UUID
	Channel         string
	ChannelTargetID pgtype.UUID
}

func (q *Queries) AddNotificationPolicyChannel(ctx context.Context, arg AddNotificationPolicyChannelParams) error {
	_, err := q.db.Exec(ctx, addNotificationPolicyChannel, arg.PolicyID, arg.Channel, arg.ChannelTargetID)
	return err
}

const addNotificationPolicyContact = `-- name: AddNotificationPolicyContact :exec
INSERT INTO notification_policy_contact (policy_id, contact_id) VALUES ($1, $2)
`

type AddNotificationPolicyContactParams struct {
	PolicyID  pgtype.UUID
	ContactID pgtype.UUID
}

func (q *Queries) AddNotificationPolicyContact(ctx context.Context, arg AddNotificationPolicyContactParams) error {
	_, err := q.db.Exec(ctx, addNotificationPolicyContact, arg.PolicyID, arg.ContactID)
	return err
}

const addNotificationPolicyContactGroup = `-- name: AddNotificationPolicyContactGroup :exec
INSERT INTO notification_policy_contact_group (policy_id, group_id) VALUES ($1, $2)
`

type AddNotificationPolicyContactGroupParams struct {
	PolicyID pgtype.UUID
	GroupID  pgtype.UUID
}

func (q *Queries) AddNotificationPolicyContactGroup(ctx context.Context, arg AddNotificationPolicyContactGroupParams) error {
	_, err := q.db.Exec(ctx, addNotificationPolicyContactGroup, arg.PolicyID, arg.GroupID)
	return err
}

const claimDueNotification = `-- name: ClaimDueNotification :one
UPDATE notification_delivery delivery
SET locked_until = $1::timestamptz + interval '30 seconds'
WHERE delivery.id = (
    SELECT candidate.id
    FROM notification_delivery candidate
    WHERE candidate.status = 'PENDING'
      AND candidate.next_attempt_at <= $1
      AND (candidate.locked_until IS NULL OR candidate.locked_until <= $1)
    ORDER BY candidate.next_attempt_at, candidate.created_at, candidate.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, alert_instance_id, event_type, channel, target, template_id, payload, status, attempt_count, next_attempt_at, locked_until, created_at, completed_at, channel_target_id
`

func (q *Queries) ClaimDueNotification(ctx context.Context, claimedAt pgtype.Timestamptz) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimDueNotification, claimedAt)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertInstanceID,
		&i.EventType,
		&i.Channel,
		&i.Target,
		&i.TemplateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ChannelTargetID,
	)
	return i, err
}

const clearMaintenanceWindowInstances = `-- name: ClearMaintenanceWindowInstances :exec
DELETE FROM maintenance_window_instance WHERE maintenance_window_id = $1
`

func (q *Queries) ClearMaintenanceWindowInstances(ctx context.Context, maintenanceWindowID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMaintenanceWindowInstances, maintenanceWindowID)
	return err
}

const clearNotificationContactGroupMembers = `-- name: ClearNotificationContactGroupMembers :exec
DELETE FROM notification_contact_group_member WHERE group_id = $1
`

func (q *Queries) ClearNotificationContactGroupMembers(ctx context.Context, groupID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearNotificationContactGroupMembers, groupID)
	return err
}

const clearNotificationPolicyChannels = `-- name: ClearNotificationPolicyChannels :exec
DELETE FROM notification_policy_channel WHERE policy_id = $1
`

func (q *Queries) ClearNotificationPolicyChannels(ctx context.Context, policyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearNotificationPolicyChannels, policyID)
	return err
}

const clearNotificationPolicyContactGroups = `-- name: ClearNotificationPolicyContactGroups :exec
DELETE FROM notification_policy_contact_group WHERE policy_id = $1
`

func (q *Queries) ClearNotificationPolicyContactGroups(ctx context.Context, policyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearNotificationPolicyContactGroups, policyID)
	return err
}

const clearNotificationPolicyContacts = `-- name: ClearNotificationPolicyContacts :exec
DELETE FROM notification_policy_contact WHERE policy_id = $1
`

func (q *Queries) ClearNotificationPolicyContacts(ctx context.Context, policyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearNotificationPolicyContacts, policyID)
	return err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one
INSERT INTO maintenance_window (
    id, starts_at, ends_at, reason, created_by, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, starts_at, ends_at, reason, created_by, created_at, updated_at, deleted_at
`

type CreateMaintenanceWindowParams struct {
	ID        pgtype.UUID
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	Reason    string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceWindow,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNotificationContact = `-- name: CreateNotificationContact :one
INSERT INTO notification_contact (id, name, email, external_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, name, email, external_id, created_at, updated_at
`

type CreateNotificationContactParams struct {
	ID         pgtype.UUID
	Name       string
	Email      string
	ExternalID pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateNotificationContact(ctx context.Context, arg CreateNotificationContactParams) (NotificationContact, error) {
	row := q.db.QueryRow(ctx, createNotificationContact,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.ExternalID,
		arg.CreatedAt,
	)
	var i NotificationContact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationContactGroup = `-- name: CreateNotificationContactGroup :one
INSERT INTO notification_contact_group (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $3)
RETURNING id, name, created_at, updated_at
`

type CreateNotificationContactGroupParams struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNotificationContactGroup(ctx context.Context, arg CreateNotificationContactGroupParams) (NotificationContactGroup, error) {
	row := q.db.QueryRow(ctx, createNotificationContactGroup, arg.ID, arg.Name, arg.CreatedAt)
	var i NotificationContactGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationPolicy = `-- name: CreateNotificationPolicy :one
INSERT INTO notification_policy (
    id, identifier, name, is_default, severity_filter, notify_on_fire,
    notify_on_recovery, repeat_interval, template_id, created_at, updated_at
)
VALUES ($1, $2, $3, false, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, identifier, name, is_default, created_at, updated_at, severity_filter, notify_on_fire, notify_on_recovery, repeat_interval, template_id
`

type CreateNotificationPolicyParams struct {
	ID               pgtype.UUID
	Identifier       string
	Name             string
	SeverityFilter   []string
	NotifyOnFire     bool
	NotifyOnRecovery bool
	RepeatInterval   int32
	TemplateID       pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateNotificationPolicy(ctx context.Context, arg CreateNotificationPolicyParams) (NotificationPolicy, error) {
	row := q.db.QueryRow(ctx, createNotificationPolicy,
		arg.ID,
		arg.Identifier,
		arg.Name,
		arg.SeverityFilter,
		arg.NotifyOnFire,
		arg.NotifyOnRecovery,
		arg.RepeatInterval,
		arg.TemplateID,
		arg.CreatedAt,
	)
	var i NotificationPolicy
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeverityFilter,
		&i.NotifyOnFire,
		&i.NotifyOnRecovery,
		&i.RepeatInterval,
		&i.TemplateID,
	)
	return i, err
}

const createWebhookTarget = `-- name: CreateWebhookTarget :one
INSERT INTO webhook_target (
    id, name, enabled, url, signing_value_ciphertext,
    signature_header_ciphertext, signing_key_version, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at
`

type CreateWebhookTargetParams struct {
	ID                        pgtype.UUID
	Name                      string
	Enabled                   bool
	Url                       string
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) CreateWebhookTarget(ctx context.Context, arg CreateWebhookTargetParams) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, createWebhookTarget,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Url,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
		arg.CreatedAt,
	)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :execrows
UPDATE maintenance_window
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteMaintenanceWindowParams struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, arg DeleteMaintenanceWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenanceWindow, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationContact = `-- name: DeleteNotificationContact :execrows
DELETE FROM notification_contact WHERE id = $1
`

func (q *Queries) DeleteNotificationContact(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationContact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationContactGroup = `-- name: DeleteNotificationContactGroup :execrows
DELETE FROM notification_contact_group WHERE id = $1
`

func (q *Queries) DeleteNotificationContactGroup(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationContactGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationPolicy = `-- name: DeleteNotificationPolicy :execrows
DELETE FROM notification_policy WHERE id = $1 AND NOT is_default
`

func (q *Queries) DeleteNotificationPolicy(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationPolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingNotification = `-- name: DeletePendingNotification :exec
DELETE FROM notification_delivery WHERE id = $1 AND status = 'PENDING'
`

func (q *Queries) DeletePendingNotification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingNotification, id)
	return err
}

const deleteWebhookTarget = `-- name: DeleteWebhookTarget :execrows
DELETE FROM webhook_target WHERE id = $1
`

func (q *Queries) DeleteWebhookTarget(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endMaintenanceWindow = `-- name: EndMaintenanceWindow :one
UPDATE maintenance_window
SET ends_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL AND starts_at <= $2 AND ends_at > $2
RETURNING id, starts_at, ends_at, reason, created_by, created_at, updated_at, deleted_at
`

type EndMaintenanceWindowParams struct {
	ID     pgtype.UUID
	EndsAt pgtype.Timestamptz
}

func (q *Queries) EndMaintenanceWindow(ctx context.Context, arg EndMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, endMaintenanceWindow, arg.ID, arg.EndsAt)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const enqueueAlertNotifications = `-- name: EnqueueAlertNotifications :many
WITH selected_policy AS (
    SELECT policy.id, policy.identifier, policy.name, policy.is_default, policy.created_at, policy.updated_at, policy.severity_filter, policy.notify_on_fire, policy.notify_on_recovery, policy.repeat_interval, policy.template_id
    FROM alert_instance alert
    JOIN alert_rule rule ON rule.id = alert.rule_id
    JOIN notification_policy policy ON policy.id = COALESCE(
        rule.notification_policy_id,
        (SELECT id FROM notification_policy WHERE is_default)
    )
    WHERE alert.id = $1
      AND alert.severity = ANY(policy.severity_filter)
      AND (($2 = 'FIRING' AND policy.notify_on_fire)
        OR ($2 = 'RECOVERY' AND policy.notify_on_recovery)
        OR $2 = 'REPEAT')
), smtp_recipients AS (
    SELECT contact.email AS target
    FROM selected_policy policy
    JOIN notification_policy_channel channel
      ON channel.policy_id = policy.id AND channel.channel = 'SMTP'
    JOIN notification_policy_contact selected_contact ON selected_contact.policy_id = policy.id
    JOIN notification_contact contact ON contact.id = selected_contact.contact_id
    UNION
    SELECT contact.email
    FROM selected_policy policy
    JOIN notification_policy_channel channel
      ON channel.policy_id = policy.id AND channel.channel = 'SMTP'
    JOIN notification_policy_contact_group selected_group ON selected_group.policy_id = policy.id
    JOIN notification_contact_group_member member ON member.group_id = selected_group.group_id
    JOIN notification_contact contact ON contact.id = member.contact_id
)
INSERT INTO notification_delivery (
    alert_instance_id, event_type, channel, channel_target_id, target, template_id,
    payload, next_attempt_at, created_at
)
SELECT $1, $2, destination.channel, destination.channel_target_id,
       destination.target, $3, $4, $5, $5
FROM (
    SELECT 'SMTP'::text AS channel, NULL::uuid AS channel_target_id, recipient.target
    FROM smtp_channel smtp
    CROSS JOIN LATERAL (
        SELECT target FROM smtp_recipients
        UNION ALL
        SELECT smtp.recipient
        WHERE NOT EXISTS (SELECT 1 FROM smtp_recipients)
          AND EXISTS (
              SELECT 1 FROM selected_policy policy
              JOIN notification_policy_channel channel
                ON channel.policy_id = policy.id AND channel.channel = 'SMTP'
          )
    ) recipient
    WHERE smtp.singleton AND smtp.enabled
    UNION ALL
    SELECT 'WEBHOOK', webhook.id, webhook.url
    FROM selected_policy policy
    JOIN notification_policy_channel channel
      ON channel.policy_id = policy.id AND channel.channel = 'WEBHOOK'
    JOIN webhook_target webhook ON webhook.id = channel.channel_target_id
    WHERE webhook.enabled
) destination
RETURNING id
`

type EnqueueAlertNotificationsParams struct {
	AlertInstanceID pgtype.UUID
	EventType       string
	TemplateID      pgtype.Text
	Payload         []byte
	NextAttemptAt   pgtype.Timestamptz
}

func (q *Queries) EnqueueAlertNotifications(ctx context.Context, arg EnqueueAlertNotificationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, enqueueAlertNotifications,
		arg.AlertInstanceID,
		arg.EventType,
		arg.TemplateID,
		arg.Payload,
		arg.NextAttemptAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueTestNotification = `-- name: EnqueueTestNotification :one
INSERT INTO notification_delivery (
    event_type, channel, target, template_id, payload, next_attempt_at, created_at
)
VALUES ('TEST', 'SMTP', $1, 'builtin.smtp.test.v1', '{}'::jsonb, $2, $2)
RETURNING id
`

type EnqueueTestNotificationParams struct {
	Target        string
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) EnqueueTestNotification(ctx context.Context, arg EnqueueTestNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueTestNotification, arg.Target, arg.NextAttemptAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const enqueueTestWebhookNotification = `-- name: EnqueueTestWebhookNotification :one
INSERT INTO notification_delivery (
    event_type, channel, channel_target_id, target, template_id, payload, next_attempt_at, created_at
)
SELECT 'TEST', 'WEBHOOK', webhook.id, webhook.url,
       'builtin.webhook.test.v1', '{}'::jsonb, $2, $2
FROM webhook_target webhook
WHERE webhook.id = $1 AND webhook.enabled
RETURNING id
`

type EnqueueTestWebhookNotificationParams struct {
	ID            pgtype.UUID
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) EnqueueTestWebhookNotification(ctx context.Context, arg EnqueueTestWebhookNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueTestWebhookNotification, arg.ID, arg.NextAttemptAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMaintenanceWindow = `-- name: GetMaintenanceWindow :one
SELECT id, starts_at, ends_at, reason, created_by, created_at, updated_at, deleted_at FROM maintenance_window
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaintenanceWindow(ctx context.Context, id pgtype.UUID) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceWindow, id)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationAlertInstance = `-- name: GetNotificationAlertInstance :one
SELECT alert.id, alert.instance_id
FROM notification_delivery delivery
JOIN alert_instance alert ON alert.id = delivery.alert_instance_id
WHERE delivery.id = $1
`

type GetNotificationAlertInstanceRow struct {
	ID         pgtype.UUID
	InstanceID pgtype.UUID
}

func (q *Queries) GetNotificationAlertInstance(ctx context.Context, id pgtype.UUID) (GetNotificationAlertInstanceRow, error) {
	row := q.db.QueryRow(ctx, getNotificationAlertInstance, id)
	var i GetNotificationAlertInstanceRow
	err := row.Scan(&i.ID, &i.InstanceID)
	return i, err
}

const getNotificationContact = `-- name: GetNotificationContact :one
SELECT id, name, email, external_id, created_at, updated_at FROM notification_contact WHERE id = $1
`

func (q *Queries) GetNotificationContact(ctx context.Context, id pgtype.UUID) (NotificationContact, error) {
	row := q.db.QueryRow(ctx, getNotificationContact, id)
	var i NotificationContact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationContactGroup = `-- name: GetNotificationContactGroup :one
SELECT id, name, created_at, updated_at FROM notification_contact_group WHERE id = $1
`

func (q *Queries) GetNotificationContactGroup(ctx context.Context, id pgtype.UUID) (NotificationContactGroup, error) {
	row := q.db.QueryRow(ctx, getNotificationContactGroup, id)
	var i NotificationContactGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationPolicy = `-- name: GetNotificationPolicy :one
SELECT id, identifier, name, is_default, created_at, updated_at, severity_filter, notify_on_fire, notify_on_recovery, repeat_interval, template_id FROM notification_policy WHERE id = $1
`

func (q *Queries) GetNotificationPolicy(ctx context.Context, id pgtype.UUID) (NotificationPolicy, error) {
	row := q.db.QueryRow(ctx, getNotificationPolicy, id)
	var i NotificationPolicy
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeverityFilter,
		&i.NotifyOnFire,
		&i.NotifyOnRecovery,
		&i.RepeatInterval,
		&i.TemplateID,
	)
	return i, err
}

const getSMTPChannel = `-- name: GetSMTPChannel :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton
`

func (q *Queries) GetSMTPChannel(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannel)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMTPChannelForKeyRotation = `-- name: GetSMTPChannelForKeyRotation :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton AND auth_key_version IS NOT NULL FOR UPDATE
`

func (q *Queries) GetSMTPChannelForKeyRotation(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannelForKeyRotation)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookTarget = `-- name: GetWebhookTarget :one
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target WHERE id = $1
`

func (q *Queries) GetWebhookTarget(ctx context.Context, id pgtype.UUID) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, getWebhookTarget, id)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveChannelFailureSummaries = `-- name: ListActiveChannelFailureSummaries :many
WITH terminal_failures AS (
    SELECT delivery.channel, delivery.channel_target_id, delivery.target,
           delivery.completed_at AS failed_at, attempt.failure_reason,
           delivery.attempt_count - 1 AS retry_count
    FROM notification_delivery delivery
    JOIN notification_attempt attempt
      ON attempt.notification_id = delivery.id
     AND attempt.retry_count = delivery.attempt_count - 1
    WHERE delivery.status = 'FAILED'
      AND (delivery.channel <> 'WEBHOOK' OR EXISTS (
          SELECT 1 FROM webhook_target webhook WHERE webhook.id = delivery.channel_target_id
      ))
      AND NOT EXISTS (
          SELECT 1
          FROM notification_delivery sent
          WHERE sent.status = 'SENT'
            AND sent.channel = delivery.channel
            AND sent.channel_target_id IS NOT DISTINCT FROM delivery.channel_target_id
            AND sent.completed_at > delivery.completed_at
      )
)
SELECT channel, channel_target_id,
       ((array_agg(target ORDER BY failed_at DESC))[1])::text AS target,
       count(*)::integer AS recent_failure_count,
       ((array_agg(failure_reason ORDER BY failed_at DESC))[1])::text AS last_failure_reason,
       max(failed_at)::timestamptz AS last_failed_at
FROM terminal_failures
GROUP BY channel, channel_target_id
ORDER BY channel, channel_target_id
`

type ListActiveChannelFailureSummariesRow struct {
	Channel            string
	ChannelTargetID    pgtype.UUID
	Target             string
	RecentFailureCount int32
	LastFailureReason  string
	LastFailedAt       pgtype.Timestamptz
}

func (q *Queries) ListActiveChannelFailureSummaries(ctx context.Context) ([]ListActiveChannelFailureSummariesRow, error) {
	rows, err := q.db.Query(ctx, listActiveChannelFailureSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChannelFailureSummariesRow
	for rows.Next() {
		var i ListActiveChannelFailureSummariesRow
		if err := rows.Scan(
			&i.Channel,
			&i.ChannelTargetID,
			&i.Target,
			&i.RecentFailureCount,
			&i.LastFailureReason,
			&i.LastFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertNotificationAttempts = `-- name: ListAlertNotificationAttempts :many
SELECT delivery.id, delivery.event_type, delivery.channel, delivery.target,
       delivery.template_id, delivery.status, delivery.attempt_count,
       delivery.created_at, delivery.completed_at,
       attempt.attempted_at, attempt.result, attempt.failure_reason, attempt.retry_count
FROM notification_delivery delivery
LEFT JOIN notification_attempt attempt ON attempt.notification_id = delivery.id
WHERE delivery.alert_instance_id = $1
ORDER BY delivery.created_at DESC, delivery.id, attempt.retry_count
`

type ListAlertNotificationAttemptsRow struct {
	ID            pgtype.UUID
	EventType     string
	Channel       string
	Target        string
	TemplateID    pgtype.Text
	Status        string
	AttemptCount  int32
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	AttemptedAt   pgtype.Timestamptz
	Result        pgtype.Text
	FailureReason pgtype.Text
	RetryCount    pgtype.Int4
}

func (q *Queries) ListAlertNotificationAttempts(ctx context.Context, alertInstanceID pgtype.UUID) ([]ListAlertNotificationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAlertNotificationAttempts, alertInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertNotificationAttemptsRow
	for rows.Next() {
		var i ListAlertNotificationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Channel,
			&i.Target,
			&i.TemplateID,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.AttemptedAt,
			&i.Result,
			&i.FailureReason,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindowInstances = `-- name: ListMaintenanceWindowInstances :many
SELECT instance_id FROM maintenance_window_instance
WHERE maintenance_window_id = $1
ORDER BY instance_id
`

func (q *Queries) ListMaintenanceWindowInstances(ctx context.Context, maintenanceWindowID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindowInstances, maintenanceWindowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var instance_id pgtype.UUID
		if err := rows.Scan(&instance_id); err != nil {
			return nil, err
		}
		items = append(items, instance_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT id, starts_at, ends_at, reason, created_by, created_at, updated_at, deleted_at FROM maintenance_window
WHERE deleted_at IS NULL
ORDER BY starts_at DESC, id
`

func (q *Queries) ListMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceWindow
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindowsForInstance = `-- name: ListMaintenanceWindowsForInstance :many
SELECT maintenance.id, maintenance.starts_at, maintenance.ends_at, maintenance.reason, maintenance.created_by, maintenance.created_at, maintenance.updated_at, maintenance.deleted_at
FROM maintenance_window maintenance
JOIN maintenance_window_instance scope ON scope.maintenance_window_id = maintenance.id
WHERE scope.instance_id = $1
  AND maintenance.deleted_at IS NULL
ORDER BY maintenance.ends_at, maintenance.id
`

func (q *Queries) ListMaintenanceWindowsForInstance(ctx context.Context, instanceID pgtype.UUID) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindowsForInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceWindow
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationContactGroupMembers = `-- name: ListNotificationContactGroupMembers :many
SELECT contact_id FROM notification_contact_group_member
WHERE group_id = $1 ORDER BY contact_id
`

func (q *Queries) ListNotificationContactGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNotificationContactGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var contact_id pgtype.UUID
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationContactGroups = `-- name: ListNotificationContactGroups :many
SELECT id, name, created_at, updated_at FROM notification_contact_group ORDER BY name, id
`

func (q *Queries) ListNotificationContactGroups(ctx context.Context) ([]NotificationContactGroup, error) {
	rows, err := q.db.Query(ctx, listNotificationContactGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationContactGroup
	for rows.Next() {
		var i NotificationContactGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationContacts = `-- name: ListNotificationContacts :many
SELECT id, name, email, external_id, created_at, updated_at FROM notification_contact ORDER BY name, id
`

func (q *Queries) ListNotificationContacts(ctx context.Context) ([]NotificationContact, error) {
	rows, err := q.db.Query(ctx, listNotificationContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationContact
	for rows.Next() {
		var i NotificationContact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPolicies = `-- name: ListNotificationPolicies :many
SELECT id, identifier, name, is_default, created_at, updated_at, severity_filter, notify_on_fire, notify_on_recovery, repeat_interval, template_id FROM notification_policy ORDER BY is_default DESC, name, id
`

func (q *Queries) ListNotificationPolicies(ctx context.Context) ([]NotificationPolicy, error) {
	rows, err := q.db.Query(ctx, listNotificationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPolicy
	for rows.Next() {
		var i NotificationPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeverityFilter,
			&i.NotifyOnFire,
			&i.NotifyOnRecovery,
			&i.RepeatInterval,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPolicyChannels = `-- name: ListNotificationPolicyChannels :many
SELECT channel, channel_target_id FROM notification_policy_channel
WHERE policy_id = $1 ORDER BY channel, channel_target_id
`

type ListNotificationPolicyChannelsRow struct {
	Channel         string
	ChannelTargetID pgtype.UUID
}

func (q *Queries) ListNotificationPolicyChannels(ctx context.Context, policyID pgtype.UUID) ([]ListNotificationPolicyChannelsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationPolicyChannels, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationPolicyChannelsRow
	for rows.Next() {
		var i ListNotificationPolicyChannelsRow
		if err := rows.Scan(&i.Channel, &i.ChannelTargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPolicyContactGroups = `-- name: ListNotificationPolicyContactGroups :many
SELECT group_id FROM notification_policy_contact_group WHERE policy_id = $1 ORDER BY group_id
`

func (q *Queries) ListNotificationPolicyContactGroups(ctx context.Context, policyID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNotificationPolicyContactGroups, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var group_id pgtype.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPolicyContacts = `-- name: ListNotificationPolicyContacts :many
SELECT contact_id FROM notification_policy_contact WHERE policy_id = $1 ORDER BY contact_id
`

func (q *Queries) ListNotificationPolicyContacts(ctx context.Context, policyID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNotificationPolicyContacts, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var contact_id pgtype.UUID
		if err := rows.Scan(&contact_id); err != nil {
			return nil, err
		}
		items = append(items, contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActiveChannelFailures = `-- name: ListRecentActiveChannelFailures :many
WITH terminal_failures AS (
    SELECT delivery.channel, delivery.channel_target_id, delivery.target,
           delivery.completed_at AS failed_at, attempt.failure_reason,
           delivery.attempt_count - 1 AS retry_count,
           row_number() OVER (
               PARTITION BY delivery.channel, delivery.channel_target_id
               ORDER BY delivery.completed_at DESC, delivery.id
           ) AS failure_number
    FROM notification_delivery delivery
    JOIN notification_attempt attempt
      ON attempt.notification_id = delivery.id
     AND attempt.retry_count = delivery.attempt_count - 1
    WHERE delivery.status = 'FAILED'
      AND (delivery.channel <> 'WEBHOOK' OR EXISTS (
          SELECT 1 FROM webhook_target webhook WHERE webhook.id = delivery.channel_target_id
      ))
      AND NOT EXISTS (
          SELECT 1
          FROM notification_delivery sent
          WHERE sent.status = 'SENT'
            AND sent.channel = delivery.channel
            AND sent.channel_target_id IS NOT DISTINCT FROM delivery.channel_target_id
            AND sent.completed_at > delivery.completed_at
      )
)
SELECT channel, channel_target_id, failed_at, target, failure_reason, retry_count
FROM terminal_failures
WHERE failure_number <= 20
ORDER BY channel, channel_target_id, failed_at DESC
`

type ListRecentActiveChannelFailuresRow struct {
	Channel         string
	ChannelTargetID pgtype.UUID
	FailedAt        pgtype.Timestamptz
	Target          string
	FailureReason   pgtype.Text
	RetryCount      int32
}

func (q *Queries) ListRecentActiveChannelFailures(ctx context.Context) ([]ListRecentActiveChannelFailuresRow, error) {
	rows, err := q.db.Query(ctx, listRecentActiveChannelFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentActiveChannelFailuresRow
	for rows.Next() {
		var i ListRecentActiveChannelFailuresRow
		if err := rows.Scan(
			&i.Channel,
			&i.ChannelTargetID,
			&i.FailedAt,
			&i.Target,
			&i.FailureReason,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepeatCandidates = `-- name: ListRepeatCandidates :many
SELECT alert.id AS alert_instance_id, alert.instance_id, alert.disposition,
       policy.repeat_interval,
       greatest(
           coalesce((SELECT max(delivery.created_at) FROM notification_delivery delivery
                     WHERE delivery.alert_instance_id = alert.id
                       AND delivery.event_type IN ('FIRING', 'REPEAT')), '-infinity'::timestamptz),
           coalesce((SELECT max(event.evaluated_at) FROM alert_event event
                     WHERE event.alert_instance_id = alert.id
                       AND event.kind = 'MAINTENANCE_SUPPRESSED'), '-infinity'::timestamptz),
           alert.first_triggered_at
       )::timestamptz AS last_notification_at,
       jsonb_build_object(
           'alert_instance_id', alert.id,
           'rule_name', coalesce(alert.rule_snapshot->>'name', rule.name),
           'instance_name', identity.name,
           'metric_id', alert.metric_id,
           'severity', alert.severity,
           'current_value', coalesce(alert.current_value::text, '')
       ) AS payload
FROM alert_instance alert
JOIN alert_rule rule ON rule.id = alert.rule_id
JOIN instance_identity identity ON identity.id = alert.instance_id
JOIN notification_policy policy ON policy.id = COALESCE(
    rule.notification_policy_id,
    (SELECT id FROM notification_policy WHERE is_default)
)
WHERE alert.status = 'FIRING'
  AND alert.first_triggered_at IS NOT NULL
  AND alert.severity = ANY(policy.severity_filter)
  AND (
      EXISTS (
          SELECT 1 FROM notification_delivery delivery
          WHERE delivery.alert_instance_id = alert.id
            AND delivery.event_type IN ('FIRING', 'REPEAT')
      )
      OR EXISTS (
          SELECT 1 FROM alert_event event
          WHERE event.alert_instance_id = alert.id
            AND event.kind = 'MAINTENANCE_SUPPRESSED'
      )
  )
  AND NOT EXISTS (
      SELECT 1 FROM notification_delivery pending
      WHERE pending.alert_instance_id = alert.id AND pending.status = 'PENDING'
  )
ORDER BY alert.id
`

type ListRepeatCandidatesRow struct {
	AlertInstanceID    pgtype.UUID
	InstanceID         pgtype.UUID
	Disposition        string
	RepeatInterval     int32
	LastNotificationAt pgtype.Timestamptz
	Payload            []byte
}

func (q *Queries) ListRepeatCandidates(ctx context.Context) ([]ListRepeatCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRepeatCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepeatCandidatesRow
	for rows.Next() {
		var i ListRepeatCandidatesRow
		if err := rows.Scan(
			&i.AlertInstanceID,
			&i.InstanceID,
			&i.Disposition,
			&i.RepeatInterval,
			&i.LastNotificationAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookTargets = `-- name: ListWebhookTargets :many
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target ORDER BY name, id
`

func (q *Queries) ListWebhookTargets(ctx context.Context) ([]WebhookTarget, error) {
	rows, err := q.db.Query(ctx, listWebhookTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookTarget
	for rows.Next() {
		var i WebhookTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Url,
			&i.SigningValueCiphertext,
			&i.SignatureHeaderCiphertext,
			&i.SigningKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookTargetsForKeyRotation = `-- name: ListWebhookTargetsForKeyRotation :many
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target ORDER BY id FOR UPDATE
`

func (q *Queries) ListWebhookTargetsForKeyRotation(ctx context.Context) ([]WebhookTarget, error) {
	rows, err := q.db.Query(ctx, listWebhookTargetsForKeyRotation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookTarget
	for rows.Next() {
		var i WebhookTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Url,
			&i.SigningValueCiphertext,
			&i.SignatureHeaderCiphertext,
			&i.SigningKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceWindowInstanceExists = `-- name: MaintenanceWindowInstanceExists :one
SELECT EXISTS (SELECT 1 FROM instance WHERE id = $1)
`

func (q *Queries) MaintenanceWindowInstanceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, maintenanceWindowInstanceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordMaintenanceSuppressed = `-- name: RecordMaintenanceSuppressed :exec
WITH marked AS (
    UPDATE alert_instance alert
    SET in_maintenance = true, maintenance_window_id = $2
    WHERE alert.id = $1
    RETURNING alert.instance_id, alert.metric_id, alert.status, alert.breach_count, alert.recovery_count, alert.no_data_count, alert.state_before_no_data, alert.unavailability, alert.updated_at, alert.id, alert.rule_id, alert.rule_version, alert.severity, alert.current_value, alert.rule_snapshot, alert.metric_dimension_key, alert.first_triggered_at, alert.first_rule_version, alert.first_rule_snapshot, alert.recovered_at, alert.disposition, alert.disposition_by, alert.disposition_at, alert.disposition_note, alert.ignore_reason_code, alert.ignore_reason_detail, alert.in_maintenance, alert.maintenance_window_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at, in_maintenance, maintenance_window_id
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'MAINTENANCE_SUPPRESSED',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $3, true, $2
FROM marked alert
`

type RecordMaintenanceSuppressedParams struct {
	ID                  pgtype.UUID
	MaintenanceWindowID pgtype.UUID
	EvaluatedAt         pgtype.Timestamptz
}

func (q *Queries) RecordMaintenanceSuppressed(ctx context.Context, arg RecordMaintenanceSuppressedParams) error {
	_, err := q.db.Exec(ctx, recordMaintenanceSuppressed, arg.ID, arg.MaintenanceWindowID, arg.EvaluatedAt)
	return err
}

const recordNotificationFailure = `-- name: RecordNotificationFailure :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, failure_reason, retry_count
    ) VALUES ($1, $2, 'FAILED', $3, $4)
), completed AS (
    UPDATE notification_delivery
    SET status = CASE WHEN $5::boolean THEN 'FAILED' ELSE 'PENDING' END,
        attempt_count = $4 + 1,
        next_attempt_at = $6,
        locked_until = NULL,
        completed_at = CASE WHEN $5::boolean THEN $2 ELSE NULL END
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_FAILED',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
WHERE $5::boolean
`

type RecordNotificationFailureParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	FailureReason  pgtype.Text
	RetryCount     int32
	Terminal       bool
	NextAttemptAt  pgtype.Timestamptz
}

func (q *Queries) RecordNotificationFailure(ctx context.Context, arg RecordNotificationFailureParams) error {
	_, err := q.db.Exec(ctx, recordNotificationFailure,
		arg.NotificationID,
		arg.EvaluatedAt,
		arg.FailureReason,
		arg.RetryCount,
		arg.Terminal,
		arg.NextAttemptAt,
	)
	return err
}

const recordNotificationSent = `-- name: RecordNotificationSent :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, retry_count
    ) VALUES ($1, $2, 'SENT', $3)
), completed AS (
    UPDATE notification_delivery
    SET status = 'SENT', attempt_count = $3 + 1,
        locked_until = NULL, completed_at = $2
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_SENT',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
`

type RecordNotificationSentParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	RetryCount     int32
}

func (q *Queries) RecordNotificationSent(ctx context.Context, arg RecordNotificationSentParams) error {
	_, err := q.db.Exec(ctx, recordNotificationSent, arg.NotificationID, arg.EvaluatedAt, arg.RetryCount)
	return err
}

const suppressNotificationForMaintenance = `-- name: SuppressNotificationForMaintenance :exec
WITH removed AS (
    DELETE FROM notification_delivery delivery
    WHERE delivery.id = $1 AND delivery.status = 'PENDING'
    RETURNING delivery.alert_instance_id
), marked AS (
    UPDATE alert_instance alert
    SET in_maintenance = true, maintenance_window_id = $2
    FROM removed
    WHERE alert.id = removed.alert_instance_id
    RETURNING alert.instance_id, alert.metric_id, alert.status, alert.breach_count, alert.recovery_count, alert.no_data_count, alert.state_before_no_data, alert.unavailability, alert.updated_at, alert.id, alert.rule_id, alert.rule_version, alert.severity, alert.current_value, alert.rule_snapshot, alert.metric_dimension_key, alert.first_triggered_at, alert.first_rule_version, alert.first_rule_snapshot, alert.recovered_at, alert.disposition, alert.disposition_by, alert.disposition_at, alert.disposition_note, alert.ignore_reason_code, alert.ignore_reason_detail, alert.in_maintenance, alert.maintenance_window_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at, in_maintenance, maintenance_window_id
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'MAINTENANCE_SUPPRESSED',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $3, true, $2
FROM marked alert
`

type SuppressNotificationForMaintenanceParams struct {
	ID                  pgtype.UUID
	MaintenanceWindowID pgtype.UUID
	EvaluatedAt         pgtype.Timestamptz
}

func (q *Queries) SuppressNotificationForMaintenance(ctx context.Context, arg SuppressNotificationForMaintenanceParams) error {
	_, err := q.db.Exec(ctx, suppressNotificationForMaintenance, arg.ID, arg.MaintenanceWindowID, arg.EvaluatedAt)
	return err
}

const updateMaintenanceWindow = `-- name: UpdateMaintenanceWindow :one
UPDATE maintenance_window
SET starts_at = $2, ends_at = $3, reason = $4, updated_at = $5
WHERE id = $1 AND deleted_at IS NULL AND ends_at > $5
RETURNING id, starts_at, ends_at, reason, created_by, created_at, updated_at, deleted_at
`

type UpdateMaintenanceWindowParams struct {
	ID        pgtype.UUID
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	Reason    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceWindow,
		arg.ID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.UpdatedAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNotificationContact = `-- name: UpdateNotificationContact :one
UPDATE notification_contact
SET name = $2, email = $3, external_id = $4, updated_at = $5
WHERE id = $1
RETURNING id, name, email, external_id, created_at, updated_at
`

type UpdateNotificationContactParams struct {
	ID         pgtype.UUID
	Name       string
	Email      string
	ExternalID pgtype.Text
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateNotificationContact(ctx context.Context, arg UpdateNotificationContactParams) (NotificationContact, error) {
	row := q.db.QueryRow(ctx, updateNotificationContact,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.ExternalID,
		arg.UpdatedAt,
	)
	var i NotificationContact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationContactGroup = `-- name: UpdateNotificationContactGroup :one
UPDATE notification_contact_group
SET name = $2, updated_at = $3
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateNotificationContactGroupParams struct {
	ID        pgtype.UUID
	Name      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateNotificationContactGroup(ctx context.Context, arg UpdateNotificationContactGroupParams) (NotificationContactGroup, error) {
	row := q.db.QueryRow(ctx, updateNotificationContactGroup, arg.ID, arg.Name, arg.UpdatedAt)
	var i NotificationContactGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationPolicy = `-- name: UpdateNotificationPolicy :one
UPDATE notification_policy
SET name = $2, severity_filter = $3, notify_on_fire = $4,
    notify_on_recovery = $5, repeat_interval = $6, template_id = $7,
    updated_at = $8
WHERE id = $1
RETURNING id, identifier, name, is_default, created_at, updated_at, severity_filter, notify_on_fire, notify_on_recovery, repeat_interval, template_id
`

type UpdateNotificationPolicyParams struct {
	ID               pgtype.UUID
	Name             string
	SeverityFilter   []string
	NotifyOnFire     bool
	NotifyOnRecovery bool
	RepeatInterval   int32
	TemplateID       pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateNotificationPolicy(ctx context.Context, arg UpdateNotificationPolicyParams) (NotificationPolicy, error) {
	row := q.db.QueryRow(ctx, updateNotificationPolicy,
		arg.ID,
		arg.Name,
		arg.SeverityFilter,
		arg.NotifyOnFire,
		arg.NotifyOnRecovery,
		arg.RepeatInterval,
		arg.TemplateID,
		arg.UpdatedAt,
	)
	var i NotificationPolicy
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SeverityFilter,
		&i.NotifyOnFire,
		&i.NotifyOnRecovery,
		&i.RepeatInterval,
		&i.TemplateID,
	)
	return i, err
}

const updateSMTPChannelAuthKey = `-- name: UpdateSMTPChannelAuthKey :exec
UPDATE smtp_channel
SET auth_ciphertext = $1, auth_key_version = $2
WHERE singleton
`

type UpdateSMTPChannelAuthKeyParams struct {
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
}

func (q *Queries) UpdateSMTPChannelAuthKey(ctx context.Context, arg UpdateSMTPChannelAuthKeyParams) error {
	_, err := q.db.Exec(ctx, updateSMTPChannelAuthKey, arg.AuthCiphertext, arg.AuthKeyVersion)
	return err
}

const updateWebhookTarget = `-- name: UpdateWebhookTarget :one
UPDATE webhook_target
SET name = $2,
    enabled = $3,
    url = $4,
    signing_value_ciphertext = $5,
    signature_header_ciphertext = $6,
    signing_key_version = $7,
    updated_at = $8
WHERE id = $1
RETURNING id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at
`

type UpdateWebhookTargetParams struct {
	ID                        pgtype.UUID
	Name                      string
	Enabled                   bool
	Url                       string
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) UpdateWebhookTarget(ctx context.Context, arg UpdateWebhookTargetParams) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, updateWebhookTarget,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Url,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
		arg.UpdatedAt,
	)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookTargetSigningKey = `-- name: UpdateWebhookTargetSigningKey :exec
UPDATE webhook_target
SET signing_value_ciphertext = $2,
    signature_header_ciphertext = $3,
    signing_key_version = $4
WHERE id = $1
`

type UpdateWebhookTargetSigningKeyParams struct {
	ID                        pgtype.UUID
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
}

func (q *Queries) UpdateWebhookTargetSigningKey(ctx context.Context, arg UpdateWebhookTargetSigningKeyParams) error {
	_, err := q.db.Exec(ctx, updateWebhookTargetSigningKey,
		arg.ID,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
	)
	return err
}

const upsertSMTPChannel = `-- name: UpsertSMTPChannel :one
INSERT INTO smtp_channel (
    singleton, enabled, host, port, from_address, recipient,
    auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
)
VALUES (true, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (singleton) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    from_address = EXCLUDED.from_address,
    recipient = EXCLUDED.recipient,
    auth_type = EXCLUDED.auth_type,
    username = EXCLUDED.username,
    auth_ciphertext = EXCLUDED.auth_ciphertext,
    auth_key_version = EXCLUDED.auth_key_version,
    tls_mode = EXCLUDED.tls_mode,
    updated_at = EXCLUDED.updated_at
RETURNING singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
`

type UpsertSMTPChannelParams struct {
	Enabled        bool
	Host           string
	Port           int32
	FromAddress    string
	Recipient      string
	AuthType       string
	Username       pgtype.Text
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
	TlsMode        string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertSMTPChannel(ctx context.Context, arg UpsertSMTPChannelParams) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, upsertSMTPChannel,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.FromAddress,
		arg.Recipient,
		arg.AuthType,
		arg.Username,
		arg.AuthCiphertext,
		arg.AuthKeyVersion,
		arg.TlsMode,
		arg.UpdatedAt,
	)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}
