// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package notify

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueNotification = `-- name: ClaimDueNotification :one
UPDATE notification_delivery delivery
SET locked_until = $1::timestamptz + interval '30 seconds'
WHERE delivery.id = (
    SELECT candidate.id
    FROM notification_delivery candidate
    WHERE candidate.status = 'PENDING'
      AND candidate.next_attempt_at <= $1
      AND (candidate.locked_until IS NULL OR candidate.locked_until <= $1)
    ORDER BY candidate.next_attempt_at, candidate.created_at, candidate.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, alert_instance_id, event_type, channel, target, template_id, payload, status, attempt_count, next_attempt_at, locked_until, created_at, completed_at, channel_target_id
`

func (q *Queries) ClaimDueNotification(ctx context.Context, claimedAt pgtype.Timestamptz) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimDueNotification, claimedAt)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertInstanceID,
		&i.EventType,
		&i.Channel,
		&i.Target,
		&i.TemplateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ChannelTargetID,
	)
	return i, err
}

const createWebhookTarget = `-- name: CreateWebhookTarget :one
INSERT INTO webhook_target (
    id, name, enabled, url, signing_value_ciphertext,
    signature_header_ciphertext, signing_key_version, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at
`

type CreateWebhookTargetParams struct {
	ID                        pgtype.UUID
	Name                      string
	Enabled                   bool
	Url                       string
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) CreateWebhookTarget(ctx context.Context, arg CreateWebhookTargetParams) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, createWebhookTarget,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Url,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
		arg.CreatedAt,
	)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookTarget = `-- name: DeleteWebhookTarget :execrows
DELETE FROM webhook_target WHERE id = $1
`

func (q *Queries) DeleteWebhookTarget(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueAlertNotifications = `-- name: EnqueueAlertNotifications :many
INSERT INTO notification_delivery (
    alert_instance_id, event_type, channel, channel_target_id, target, template_id,
    payload, next_attempt_at, created_at
)
SELECT $1, $2, destination.channel, destination.channel_target_id,
       destination.target, $3, $4, $5, $5
FROM (
    SELECT 'SMTP'::text AS channel, NULL::uuid AS channel_target_id, smtp.recipient AS target
    FROM smtp_channel smtp
    WHERE smtp.singleton AND smtp.enabled
    UNION ALL
    SELECT 'WEBHOOK', webhook.id, webhook.url
    FROM webhook_target webhook
    WHERE webhook.enabled
) destination
RETURNING id
`

type EnqueueAlertNotificationsParams struct {
	AlertInstanceID pgtype.UUID
	EventType       string
	TemplateID      pgtype.Text
	Payload         []byte
	NextAttemptAt   pgtype.Timestamptz
}

func (q *Queries) EnqueueAlertNotifications(ctx context.Context, arg EnqueueAlertNotificationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, enqueueAlertNotifications,
		arg.AlertInstanceID,
		arg.EventType,
		arg.TemplateID,
		arg.Payload,
		arg.NextAttemptAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueTestNotification = `-- name: EnqueueTestNotification :one
INSERT INTO notification_delivery (
    event_type, channel, target, template_id, payload, next_attempt_at, created_at
)
VALUES ('TEST', 'SMTP', $1, 'builtin.smtp.test.v1', '{}'::jsonb, $2, $2)
RETURNING id
`

type EnqueueTestNotificationParams struct {
	Target        string
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) EnqueueTestNotification(ctx context.Context, arg EnqueueTestNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueTestNotification, arg.Target, arg.NextAttemptAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const enqueueTestWebhookNotification = `-- name: EnqueueTestWebhookNotification :one
INSERT INTO notification_delivery (
    event_type, channel, channel_target_id, target, template_id, payload, next_attempt_at, created_at
)
SELECT 'TEST', 'WEBHOOK', webhook.id, webhook.url,
       'builtin.webhook.test.v1', '{}'::jsonb, $2, $2
FROM webhook_target webhook
WHERE webhook.id = $1 AND webhook.enabled
RETURNING id
`

type EnqueueTestWebhookNotificationParams struct {
	ID            pgtype.UUID
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) EnqueueTestWebhookNotification(ctx context.Context, arg EnqueueTestWebhookNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueTestWebhookNotification, arg.ID, arg.NextAttemptAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSMTPChannel = `-- name: GetSMTPChannel :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton
`

func (q *Queries) GetSMTPChannel(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannel)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMTPChannelForKeyRotation = `-- name: GetSMTPChannelForKeyRotation :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton AND auth_key_version IS NOT NULL FOR UPDATE
`

func (q *Queries) GetSMTPChannelForKeyRotation(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannelForKeyRotation)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookTarget = `-- name: GetWebhookTarget :one
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target WHERE id = $1
`

func (q *Queries) GetWebhookTarget(ctx context.Context, id pgtype.UUID) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, getWebhookTarget, id)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveChannelFailureSummaries = `-- name: ListActiveChannelFailureSummaries :many
WITH terminal_failures AS (
    SELECT delivery.channel, delivery.channel_target_id, delivery.target,
           delivery.completed_at AS failed_at, attempt.failure_reason,
           delivery.attempt_count - 1 AS retry_count
    FROM notification_delivery delivery
    JOIN notification_attempt attempt
      ON attempt.notification_id = delivery.id
     AND attempt.retry_count = delivery.attempt_count - 1
    WHERE delivery.status = 'FAILED'
      AND (delivery.channel <> 'WEBHOOK' OR EXISTS (
          SELECT 1 FROM webhook_target webhook WHERE webhook.id = delivery.channel_target_id
      ))
      AND NOT EXISTS (
          SELECT 1
          FROM notification_delivery sent
          WHERE sent.status = 'SENT'
            AND sent.channel = delivery.channel
            AND sent.channel_target_id IS NOT DISTINCT FROM delivery.channel_target_id
            AND sent.completed_at > delivery.completed_at
      )
)
SELECT channel, channel_target_id,
       ((array_agg(target ORDER BY failed_at DESC))[1])::text AS target,
       count(*)::integer AS recent_failure_count,
       ((array_agg(failure_reason ORDER BY failed_at DESC))[1])::text AS last_failure_reason,
       max(failed_at)::timestamptz AS last_failed_at
FROM terminal_failures
GROUP BY channel, channel_target_id
ORDER BY channel, channel_target_id
`

type ListActiveChannelFailureSummariesRow struct {
	Channel            string
	ChannelTargetID    pgtype.UUID
	Target             string
	RecentFailureCount int32
	LastFailureReason  string
	LastFailedAt       pgtype.Timestamptz
}

func (q *Queries) ListActiveChannelFailureSummaries(ctx context.Context) ([]ListActiveChannelFailureSummariesRow, error) {
	rows, err := q.db.Query(ctx, listActiveChannelFailureSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChannelFailureSummariesRow
	for rows.Next() {
		var i ListActiveChannelFailureSummariesRow
		if err := rows.Scan(
			&i.Channel,
			&i.ChannelTargetID,
			&i.Target,
			&i.RecentFailureCount,
			&i.LastFailureReason,
			&i.LastFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertNotificationAttempts = `-- name: ListAlertNotificationAttempts :many
SELECT delivery.id, delivery.event_type, delivery.channel, delivery.target,
       delivery.template_id, delivery.status, delivery.attempt_count,
       delivery.created_at, delivery.completed_at,
       attempt.attempted_at, attempt.result, attempt.failure_reason, attempt.retry_count
FROM notification_delivery delivery
LEFT JOIN notification_attempt attempt ON attempt.notification_id = delivery.id
WHERE delivery.alert_instance_id = $1
ORDER BY delivery.created_at DESC, delivery.id, attempt.retry_count
`

type ListAlertNotificationAttemptsRow struct {
	ID            pgtype.UUID
	EventType     string
	Channel       string
	Target        string
	TemplateID    pgtype.Text
	Status        string
	AttemptCount  int32
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	AttemptedAt   pgtype.Timestamptz
	Result        pgtype.Text
	FailureReason pgtype.Text
	RetryCount    pgtype.Int4
}

func (q *Queries) ListAlertNotificationAttempts(ctx context.Context, alertInstanceID pgtype.UUID) ([]ListAlertNotificationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAlertNotificationAttempts, alertInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertNotificationAttemptsRow
	for rows.Next() {
		var i ListAlertNotificationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Channel,
			&i.Target,
			&i.TemplateID,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.AttemptedAt,
			&i.Result,
			&i.FailureReason,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActiveChannelFailures = `-- name: ListRecentActiveChannelFailures :many
WITH terminal_failures AS (
    SELECT delivery.channel, delivery.channel_target_id, delivery.target,
           delivery.completed_at AS failed_at, attempt.failure_reason,
           delivery.attempt_count - 1 AS retry_count,
           row_number() OVER (
               PARTITION BY delivery.channel, delivery.channel_target_id
               ORDER BY delivery.completed_at DESC, delivery.id
           ) AS failure_number
    FROM notification_delivery delivery
    JOIN notification_attempt attempt
      ON attempt.notification_id = delivery.id
     AND attempt.retry_count = delivery.attempt_count - 1
    WHERE delivery.status = 'FAILED'
      AND (delivery.channel <> 'WEBHOOK' OR EXISTS (
          SELECT 1 FROM webhook_target webhook WHERE webhook.id = delivery.channel_target_id
      ))
      AND NOT EXISTS (
          SELECT 1
          FROM notification_delivery sent
          WHERE sent.status = 'SENT'
            AND sent.channel = delivery.channel
            AND sent.channel_target_id IS NOT DISTINCT FROM delivery.channel_target_id
            AND sent.completed_at > delivery.completed_at
      )
)
SELECT channel, channel_target_id, failed_at, target, failure_reason, retry_count
FROM terminal_failures
WHERE failure_number <= 20
ORDER BY channel, channel_target_id, failed_at DESC
`

type ListRecentActiveChannelFailuresRow struct {
	Channel         string
	ChannelTargetID pgtype.UUID
	FailedAt        pgtype.Timestamptz
	Target          string
	FailureReason   pgtype.Text
	RetryCount      int32
}

func (q *Queries) ListRecentActiveChannelFailures(ctx context.Context) ([]ListRecentActiveChannelFailuresRow, error) {
	rows, err := q.db.Query(ctx, listRecentActiveChannelFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentActiveChannelFailuresRow
	for rows.Next() {
		var i ListRecentActiveChannelFailuresRow
		if err := rows.Scan(
			&i.Channel,
			&i.ChannelTargetID,
			&i.FailedAt,
			&i.Target,
			&i.FailureReason,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookTargets = `-- name: ListWebhookTargets :many
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target ORDER BY name, id
`

func (q *Queries) ListWebhookTargets(ctx context.Context) ([]WebhookTarget, error) {
	rows, err := q.db.Query(ctx, listWebhookTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookTarget
	for rows.Next() {
		var i WebhookTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Url,
			&i.SigningValueCiphertext,
			&i.SignatureHeaderCiphertext,
			&i.SigningKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookTargetsForKeyRotation = `-- name: ListWebhookTargetsForKeyRotation :many
SELECT id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at FROM webhook_target ORDER BY id FOR UPDATE
`

func (q *Queries) ListWebhookTargetsForKeyRotation(ctx context.Context) ([]WebhookTarget, error) {
	rows, err := q.db.Query(ctx, listWebhookTargetsForKeyRotation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookTarget
	for rows.Next() {
		var i WebhookTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Url,
			&i.SigningValueCiphertext,
			&i.SignatureHeaderCiphertext,
			&i.SigningKeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNotificationFailure = `-- name: RecordNotificationFailure :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, failure_reason, retry_count
    ) VALUES ($1, $2, 'FAILED', $3, $4)
), completed AS (
    UPDATE notification_delivery
    SET status = CASE WHEN $5::boolean THEN 'FAILED' ELSE 'PENDING' END,
        attempt_count = $4 + 1,
        next_attempt_at = $6,
        locked_until = NULL,
        completed_at = CASE WHEN $5::boolean THEN $2 ELSE NULL END
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_FAILED',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
WHERE $5::boolean
`

type RecordNotificationFailureParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	FailureReason  pgtype.Text
	RetryCount     int32
	Terminal       bool
	NextAttemptAt  pgtype.Timestamptz
}

func (q *Queries) RecordNotificationFailure(ctx context.Context, arg RecordNotificationFailureParams) error {
	_, err := q.db.Exec(ctx, recordNotificationFailure,
		arg.NotificationID,
		arg.EvaluatedAt,
		arg.FailureReason,
		arg.RetryCount,
		arg.Terminal,
		arg.NextAttemptAt,
	)
	return err
}

const recordNotificationSent = `-- name: RecordNotificationSent :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, retry_count
    ) VALUES ($1, $2, 'SENT', $3)
), completed AS (
    UPDATE notification_delivery
    SET status = 'SENT', attempt_count = $3 + 1,
        locked_until = NULL, completed_at = $2
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_SENT',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
`

type RecordNotificationSentParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	RetryCount     int32
}

func (q *Queries) RecordNotificationSent(ctx context.Context, arg RecordNotificationSentParams) error {
	_, err := q.db.Exec(ctx, recordNotificationSent, arg.NotificationID, arg.EvaluatedAt, arg.RetryCount)
	return err
}

const updateSMTPChannelAuthKey = `-- name: UpdateSMTPChannelAuthKey :exec
UPDATE smtp_channel
SET auth_ciphertext = $1, auth_key_version = $2
WHERE singleton
`

type UpdateSMTPChannelAuthKeyParams struct {
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
}

func (q *Queries) UpdateSMTPChannelAuthKey(ctx context.Context, arg UpdateSMTPChannelAuthKeyParams) error {
	_, err := q.db.Exec(ctx, updateSMTPChannelAuthKey, arg.AuthCiphertext, arg.AuthKeyVersion)
	return err
}

const updateWebhookTarget = `-- name: UpdateWebhookTarget :one
UPDATE webhook_target
SET name = $2,
    enabled = $3,
    url = $4,
    signing_value_ciphertext = $5,
    signature_header_ciphertext = $6,
    signing_key_version = $7,
    updated_at = $8
WHERE id = $1
RETURNING id, name, enabled, url, signing_value_ciphertext, signature_header_ciphertext, signing_key_version, created_at, updated_at
`

type UpdateWebhookTargetParams struct {
	ID                        pgtype.UUID
	Name                      string
	Enabled                   bool
	Url                       string
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) UpdateWebhookTarget(ctx context.Context, arg UpdateWebhookTargetParams) (WebhookTarget, error) {
	row := q.db.QueryRow(ctx, updateWebhookTarget,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Url,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
		arg.UpdatedAt,
	)
	var i WebhookTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Url,
		&i.SigningValueCiphertext,
		&i.SignatureHeaderCiphertext,
		&i.SigningKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookTargetSigningKey = `-- name: UpdateWebhookTargetSigningKey :exec
UPDATE webhook_target
SET signing_value_ciphertext = $2,
    signature_header_ciphertext = $3,
    signing_key_version = $4
WHERE id = $1
`

type UpdateWebhookTargetSigningKeyParams struct {
	ID                        pgtype.UUID
	SigningValueCiphertext    []byte
	SignatureHeaderCiphertext []byte
	SigningKeyVersion         int32
}

func (q *Queries) UpdateWebhookTargetSigningKey(ctx context.Context, arg UpdateWebhookTargetSigningKeyParams) error {
	_, err := q.db.Exec(ctx, updateWebhookTargetSigningKey,
		arg.ID,
		arg.SigningValueCiphertext,
		arg.SignatureHeaderCiphertext,
		arg.SigningKeyVersion,
	)
	return err
}

const upsertSMTPChannel = `-- name: UpsertSMTPChannel :one
INSERT INTO smtp_channel (
    singleton, enabled, host, port, from_address, recipient,
    auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
)
VALUES (true, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (singleton) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    from_address = EXCLUDED.from_address,
    recipient = EXCLUDED.recipient,
    auth_type = EXCLUDED.auth_type,
    username = EXCLUDED.username,
    auth_ciphertext = EXCLUDED.auth_ciphertext,
    auth_key_version = EXCLUDED.auth_key_version,
    tls_mode = EXCLUDED.tls_mode,
    updated_at = EXCLUDED.updated_at
RETURNING singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
`

type UpsertSMTPChannelParams struct {
	Enabled        bool
	Host           string
	Port           int32
	FromAddress    string
	Recipient      string
	AuthType       string
	Username       pgtype.Text
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
	TlsMode        string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertSMTPChannel(ctx context.Context, arg UpsertSMTPChannelParams) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, upsertSMTPChannel,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.FromAddress,
		arg.Recipient,
		arg.AuthType,
		arg.Username,
		arg.AuthCiphertext,
		arg.AuthKeyVersion,
		arg.TlsMode,
		arg.UpdatedAt,
	)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}
