// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package notify

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueNotification = `-- name: ClaimDueNotification :one
UPDATE notification_delivery delivery
SET locked_until = $1::timestamptz + interval '30 seconds'
WHERE delivery.id = (
    SELECT candidate.id
    FROM notification_delivery candidate
    WHERE candidate.status = 'PENDING'
      AND candidate.next_attempt_at <= $1
      AND (candidate.locked_until IS NULL OR candidate.locked_until <= $1)
    ORDER BY candidate.next_attempt_at, candidate.created_at, candidate.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, alert_instance_id, event_type, channel, target, template_id, payload, status, attempt_count, next_attempt_at, locked_until, created_at, completed_at
`

func (q *Queries) ClaimDueNotification(ctx context.Context, claimedAt pgtype.Timestamptz) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimDueNotification, claimedAt)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertInstanceID,
		&i.EventType,
		&i.Channel,
		&i.Target,
		&i.TemplateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const enqueueAlertNotification = `-- name: EnqueueAlertNotification :one
INSERT INTO notification_delivery (
    alert_instance_id, event_type, channel, target, template_id,
    payload, next_attempt_at, created_at
)
SELECT $1, $2, 'SMTP', smtp.recipient, $3, $4, $5, $5
FROM smtp_channel smtp
WHERE smtp.singleton AND smtp.enabled
RETURNING id
`

type EnqueueAlertNotificationParams struct {
	AlertInstanceID pgtype.UUID
	EventType       string
	TemplateID      pgtype.Text
	Payload         []byte
	NextAttemptAt   pgtype.Timestamptz
}

func (q *Queries) EnqueueAlertNotification(ctx context.Context, arg EnqueueAlertNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueAlertNotification,
		arg.AlertInstanceID,
		arg.EventType,
		arg.TemplateID,
		arg.Payload,
		arg.NextAttemptAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const enqueueTestNotification = `-- name: EnqueueTestNotification :one
INSERT INTO notification_delivery (
    event_type, channel, target, template_id, payload, next_attempt_at, created_at
)
VALUES ('TEST', 'SMTP', $1, 'builtin.smtp.test.v1', '{}'::jsonb, $2, $2)
RETURNING id
`

type EnqueueTestNotificationParams struct {
	Target        string
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) EnqueueTestNotification(ctx context.Context, arg EnqueueTestNotificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueTestNotification, arg.Target, arg.NextAttemptAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSMTPChannel = `-- name: GetSMTPChannel :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton
`

func (q *Queries) GetSMTPChannel(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannel)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMTPChannelForKeyRotation = `-- name: GetSMTPChannelForKeyRotation :one
SELECT singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at FROM smtp_channel WHERE singleton AND auth_key_version IS NOT NULL FOR UPDATE
`

func (q *Queries) GetSMTPChannelForKeyRotation(ctx context.Context) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, getSMTPChannelForKeyRotation)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertNotificationAttempts = `-- name: ListAlertNotificationAttempts :many
SELECT delivery.id, delivery.event_type, delivery.channel, delivery.target,
       delivery.template_id, delivery.status, delivery.attempt_count,
       delivery.created_at, delivery.completed_at,
       attempt.attempted_at, attempt.result, attempt.failure_reason, attempt.retry_count
FROM notification_delivery delivery
LEFT JOIN notification_attempt attempt ON attempt.notification_id = delivery.id
WHERE delivery.alert_instance_id = $1
ORDER BY delivery.created_at DESC, delivery.id, attempt.retry_count
`

type ListAlertNotificationAttemptsRow struct {
	ID            pgtype.UUID
	EventType     string
	Channel       string
	Target        string
	TemplateID    pgtype.Text
	Status        string
	AttemptCount  int32
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	AttemptedAt   pgtype.Timestamptz
	Result        pgtype.Text
	FailureReason pgtype.Text
	RetryCount    pgtype.Int4
}

func (q *Queries) ListAlertNotificationAttempts(ctx context.Context, alertInstanceID pgtype.UUID) ([]ListAlertNotificationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAlertNotificationAttempts, alertInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertNotificationAttemptsRow
	for rows.Next() {
		var i ListAlertNotificationAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Channel,
			&i.Target,
			&i.TemplateID,
			&i.Status,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.AttemptedAt,
			&i.Result,
			&i.FailureReason,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNotificationFailure = `-- name: RecordNotificationFailure :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, failure_reason, retry_count
    ) VALUES ($1, $2, 'FAILED', $3, $4)
), completed AS (
    UPDATE notification_delivery
    SET status = CASE WHEN $5::boolean THEN 'FAILED' ELSE 'PENDING' END,
        attempt_count = $4 + 1,
        next_attempt_at = $6,
        locked_until = NULL,
        completed_at = CASE WHEN $5::boolean THEN $2 ELSE NULL END
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_FAILED',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
WHERE $5::boolean
`

type RecordNotificationFailureParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	FailureReason  pgtype.Text
	RetryCount     int32
	Terminal       bool
	NextAttemptAt  pgtype.Timestamptz
}

func (q *Queries) RecordNotificationFailure(ctx context.Context, arg RecordNotificationFailureParams) error {
	_, err := q.db.Exec(ctx, recordNotificationFailure,
		arg.NotificationID,
		arg.EvaluatedAt,
		arg.FailureReason,
		arg.RetryCount,
		arg.Terminal,
		arg.NextAttemptAt,
	)
	return err
}

const recordNotificationSent = `-- name: RecordNotificationSent :exec
WITH attempt AS (
    INSERT INTO notification_attempt (
        notification_id, attempted_at, result, retry_count
    ) VALUES ($1, $2, 'SENT', $3)
), completed AS (
    UPDATE notification_delivery
    SET status = 'SENT', attempt_count = $3 + 1,
        locked_until = NULL, completed_at = $2
    WHERE id = $1 AND status = 'PENDING'
    RETURNING alert_instance_id
)
INSERT INTO alert_event (
    alert_instance_id, rule_id, rule_version, kind,
    from_state, to_state, current_value, unavailability,
    rule_snapshot, evaluated_at
)
SELECT alert.id, alert.rule_id, alert.rule_version, 'NOTIFICATION_SENT',
       alert.status, alert.status, alert.current_value, alert.unavailability,
       alert.rule_snapshot, $2
FROM completed
JOIN alert_instance alert ON alert.id = completed.alert_instance_id
`

type RecordNotificationSentParams struct {
	NotificationID pgtype.UUID
	EvaluatedAt    pgtype.Timestamptz
	RetryCount     int32
}

func (q *Queries) RecordNotificationSent(ctx context.Context, arg RecordNotificationSentParams) error {
	_, err := q.db.Exec(ctx, recordNotificationSent, arg.NotificationID, arg.EvaluatedAt, arg.RetryCount)
	return err
}

const updateSMTPChannelAuthKey = `-- name: UpdateSMTPChannelAuthKey :exec
UPDATE smtp_channel
SET auth_ciphertext = $1, auth_key_version = $2
WHERE singleton
`

type UpdateSMTPChannelAuthKeyParams struct {
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
}

func (q *Queries) UpdateSMTPChannelAuthKey(ctx context.Context, arg UpdateSMTPChannelAuthKeyParams) error {
	_, err := q.db.Exec(ctx, updateSMTPChannelAuthKey, arg.AuthCiphertext, arg.AuthKeyVersion)
	return err
}

const upsertSMTPChannel = `-- name: UpsertSMTPChannel :one
INSERT INTO smtp_channel (
    singleton, enabled, host, port, from_address, recipient,
    auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
)
VALUES (true, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (singleton) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    from_address = EXCLUDED.from_address,
    recipient = EXCLUDED.recipient,
    auth_type = EXCLUDED.auth_type,
    username = EXCLUDED.username,
    auth_ciphertext = EXCLUDED.auth_ciphertext,
    auth_key_version = EXCLUDED.auth_key_version,
    tls_mode = EXCLUDED.tls_mode,
    updated_at = EXCLUDED.updated_at
RETURNING singleton, enabled, host, port, from_address, recipient, auth_type, username, auth_ciphertext, auth_key_version, tls_mode, updated_at
`

type UpsertSMTPChannelParams struct {
	Enabled        bool
	Host           string
	Port           int32
	FromAddress    string
	Recipient      string
	AuthType       string
	Username       pgtype.Text
	AuthCiphertext []byte
	AuthKeyVersion pgtype.Int4
	TlsMode        string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertSMTPChannel(ctx context.Context, arg UpsertSMTPChannelParams) (SmtpChannel, error) {
	row := q.db.QueryRow(ctx, upsertSMTPChannel,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.FromAddress,
		arg.Recipient,
		arg.AuthType,
		arg.Username,
		arg.AuthCiphertext,
		arg.AuthKeyVersion,
		arg.TlsMode,
		arg.UpdatedAt,
	)
	var i SmtpChannel
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.FromAddress,
		&i.Recipient,
		&i.AuthType,
		&i.Username,
		&i.AuthCiphertext,
		&i.AuthKeyVersion,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}
