/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInstances"];
        put?: never;
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getInstance"];
        put: operations["updateInstance"];
        post?: never;
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/metrics/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetricSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlertRules"];
        put?: never;
        post: operations["createAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportAgentMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Unavailability: "NO_SAMPLES_YET" | "NO_DATA_IN_RANGE" | "STALE" | "COLLECTION_PAUSED" | "COLLECTION_FAILED" | "DB_UNREACHABLE" | "AGENT_OFFLINE" | "PERMISSION_DENIED" | "EXTENSION_MISSING" | "FEATURE_DISABLED" | "VERSION_UNSUPPORTED" | "NOT_APPLICABLE_ROLE" | "COUNTER_RESET";
        /** @enum {string} */
        AlertStatus: "OK" | "PENDING" | "FIRING" | "NO_DATA" | "RECOVERED";
        /** @enum {string} */
        CapabilityStatus: "PRESENT" | "MISSING" | "NOT_APPLICABLE" | "UNKNOWN";
        /** @enum {string} */
        AlertAggregation: "latest" | "avg" | "max" | "min" | "sum" | "count";
        /** @enum {string} */
        AlertOperator: ">" | ">=" | "<" | "<=" | "=" | "!=";
        /** @enum {string} */
        AlertSeverity: "critical" | "warning" | "info";
        /** @enum {string} */
        NoDataPolicy: "ignore" | "mark_no_data";
        AlertRuleInput: {
            name: string;
            metric_id: string;
            aggregation: components["schemas"]["AlertAggregation"];
            operator: components["schemas"]["AlertOperator"];
            /** Format: double */
            threshold: number;
            recovery_operator: components["schemas"]["AlertOperator"];
            /** Format: double */
            recovery_threshold: number;
            window_seconds: number;
            consecutive_count: number;
            recovery_consecutive_count: number;
            severity: components["schemas"]["AlertSeverity"];
            no_data_policy: components["schemas"]["NoDataPolicy"];
            enabled: boolean;
        };
        AlertRule: {
            /** Format: uuid */
            id: string;
            name: string;
            metric_id: string;
            aggregation: components["schemas"]["AlertAggregation"];
            operator: components["schemas"]["AlertOperator"];
            /** Format: double */
            threshold: number;
            recovery_operator: components["schemas"]["AlertOperator"];
            /** Format: double */
            recovery_threshold: number;
            window_seconds: number;
            consecutive_count: number;
            recovery_consecutive_count: number;
            severity: components["schemas"]["AlertSeverity"];
            no_data_policy: components["schemas"]["NoDataPolicy"];
            enabled: boolean;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        InstanceInput: {
            name: string;
            host: string;
            port: number;
            database: string;
            username: string;
            password: string;
        };
        Instance: {
            /** Format: uuid */
            id: string;
            name: string;
            host: string;
            port: number;
            database: string;
            username: string;
            alert_status: components["schemas"]["AlertStatus"];
        };
        InstanceCreated: {
            instance: components["schemas"]["Instance"];
            /** @description Returned once when the instance is created. */
            agent_token: string;
        };
        MetricSeriesResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            step: string;
            metrics: {
                metric: string;
                unit: string;
                unavailability: components["schemas"]["Unavailability"] | null;
                series: {
                    labels: {
                        [key: string]: string;
                    };
                    points: (number | null)[][];
                }[];
            }[];
        };
        AgentReport: {
            /** Format: uuid */
            instance_id: string;
            /** Format: date-time */
            timestamp: string;
            metrics: {
                /** @enum {string} */
                metric: "host.cpu.usage_percent" | "host.memory.usage_percent" | "host.disk.usage_percent" | "host.disk.free_bytes" | "host.disk.iops" | "host.disk.throughput_bytes_per_sec" | "host.network.bytes_per_sec";
                value: number;
            }[];
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INTERNAL";
                message: string;
                field_errors?: {
                    field: string;
                    message: string;
                }[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            204: {
                headers: {
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"][];
                };
            };
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreated"];
                };
            };
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
        };
    };
    updateInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetricSeries: {
        parameters: {
            query: {
                metric: ("pg.availability.reachable" | "pg.probe.latency_ms" | "collector.last_success_time" | "agent.status" | "host.cpu.usage_percent" | "host.memory.usage_percent" | "host.disk.usage_percent" | "host.disk.free_bytes" | "host.disk.iops" | "host.disk.throughput_bytes_per_sec" | "host.network.bytes_per_sec" | "pg.connection.total" | "pg.connection.active" | "pg.connection.idle_in_transaction" | "pg.tps" | "pg.xact.commit_per_sec" | "pg.xact.rollback_per_sec" | "pg.tuples.read_per_sec" | "pg.tuples.write_per_sec" | "pg.temp.files_per_sec" | "pg.temp.bytes_per_sec" | "pg.transaction.long_count" | "pg.transaction.max_duration_sec" | "pg.lock.waiting_count" | "pg.session.blocked_count" | "pg.query.long_running_count" | "pg.prepared_xacts.count" | "pg.replication.role" | "pg.replication.connection_state" | "pg.replication.replay_lag_ms" | "pg.replication.wal_lag_bytes" | "pg.replication_slot.retained_wal_bytes")[];
                from: string;
                to: string;
                step?: "auto" | "15s" | "1m" | "5m" | "raw";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metric series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeriesResponse"];
                };
            };
            /** @description Invalid time range or step */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"][];
                };
            };
        };
    };
    createAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Invalid alert rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reportAgentMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentReport"];
            };
        };
        responses: {
            /** @description Accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid timestamp */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
