// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package alerting

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlertStatus = `-- name: GetAlertStatus :one
SELECT status FROM alert_instance WHERE instance_id = $1
`

func (q *Queries) GetAlertStatus(ctx context.Context, instanceID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAlertStatus, instanceID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getEvaluationTarget = `-- name: GetEvaluationTarget :one
SELECT i.id,
       s.last_success_at,
       s.last_error_code,
       a.status,
       a.breach_count,
       a.recovery_count,
       a.no_data_count,
       a.state_before_no_data
FROM instance i
LEFT JOIN instance_collect_state s
  ON s.instance_id = i.id AND s.source = 'SERVER_DIRECT'
LEFT JOIN alert_instance a ON a.instance_id = i.id
WHERE i.id = $1
`

type GetEvaluationTargetRow struct {
	ID                pgtype.UUID
	LastSuccessAt     pgtype.Timestamptz
	LastErrorCode     pgtype.Text
	Status            pgtype.Text
	BreachCount       pgtype.Int4
	RecoveryCount     pgtype.Int4
	NoDataCount       pgtype.Int4
	StateBeforeNoData pgtype.Text
}

func (q *Queries) GetEvaluationTarget(ctx context.Context, id pgtype.UUID) (GetEvaluationTargetRow, error) {
	row := q.db.QueryRow(ctx, getEvaluationTarget, id)
	var i GetEvaluationTargetRow
	err := row.Scan(
		&i.ID,
		&i.LastSuccessAt,
		&i.LastErrorCode,
		&i.Status,
		&i.BreachCount,
		&i.RecoveryCount,
		&i.NoDataCount,
		&i.StateBeforeNoData,
	)
	return i, err
}

const latestConnectionPoint = `-- name: LatestConnectionPoint :one
SELECT ms.ts, ms.value
FROM metric_series series
JOIN metric_sample ms ON ms.series_id = series.series_id
WHERE series.instance_id = $1
  AND series.metric_id = 'pg.connection.total'
  AND ms.ts > $2
ORDER BY ms.ts DESC
LIMIT 1
`

type LatestConnectionPointParams struct {
	InstanceID pgtype.UUID
	Ts         pgtype.Timestamptz
}

type LatestConnectionPointRow struct {
	Ts    pgtype.Timestamptz
	Value float64
}

func (q *Queries) LatestConnectionPoint(ctx context.Context, arg LatestConnectionPointParams) (LatestConnectionPointRow, error) {
	row := q.db.QueryRow(ctx, latestConnectionPoint, arg.InstanceID, arg.Ts)
	var i LatestConnectionPointRow
	err := row.Scan(&i.Ts, &i.Value)
	return i, err
}

const listEvaluationTargetIDs = `-- name: ListEvaluationTargetIDs :many
SELECT id FROM instance ORDER BY id
`

func (q *Queries) ListEvaluationTargetIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEvaluationTargetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAlertSnapshot = `-- name: SaveAlertSnapshot :exec
INSERT INTO alert_instance (
    instance_id, metric_id, status, breach_count, recovery_count,
    no_data_count, state_before_no_data, unavailability, updated_at
)
VALUES ($1, 'pg.connection.total', $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (instance_id)
DO UPDATE SET status = EXCLUDED.status,
              breach_count = EXCLUDED.breach_count,
              recovery_count = EXCLUDED.recovery_count,
              no_data_count = EXCLUDED.no_data_count,
              state_before_no_data = EXCLUDED.state_before_no_data,
              unavailability = EXCLUDED.unavailability,
              updated_at = EXCLUDED.updated_at
`

type SaveAlertSnapshotParams struct {
	InstanceID        pgtype.UUID
	Status            string
	BreachCount       int32
	RecoveryCount     int32
	NoDataCount       int32
	StateBeforeNoData pgtype.Text
	Unavailability    pgtype.Text
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) SaveAlertSnapshot(ctx context.Context, arg SaveAlertSnapshotParams) error {
	_, err := q.db.Exec(ctx, saveAlertSnapshot,
		arg.InstanceID,
		arg.Status,
		arg.BreachCount,
		arg.RecoveryCount,
		arg.NoDataCount,
		arg.StateBeforeNoData,
		arg.Unavailability,
		arg.UpdatedAt,
	)
	return err
}
