// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package httpapi

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS (SELECT 1 FROM app_user WHERE role = 'PLATFORM_ADMIN')
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO app_user (id, username, password_hash, role)
VALUES ($1, $2, $3, 'PLATFORM_ADMIN')
ON CONFLICT (username) DO NOTHING
`

type CreateAdminParams struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash []byte
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.Exec(ctx, createAdmin, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_session (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const getAgentTokenHash = `-- name: GetAgentTokenHash :one
SELECT agent_token_hash FROM instance WHERE id = $1
`

func (q *Queries) GetAgentTokenHash(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAgentTokenHash, id)
	var agent_token_hash []byte
	err := row.Scan(&agent_token_hash)
	return agent_token_hash, err
}

const getInstanceAlertStatus = `-- name: GetInstanceAlertStatus :one
SELECT status FROM alert_instance WHERE instance_id = $1
`

func (q *Queries) GetInstanceAlertStatus(ctx context.Context, instanceID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getInstanceAlertStatus, instanceID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT u.id, u.role
FROM user_session session
JOIN app_user u ON u.id = session.user_id
WHERE session.token_hash = $1 AND session.expires_at > $2
`

type GetSessionPrincipalParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type GetSessionPrincipalRow struct {
	ID   pgtype.UUID
	Role string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, arg GetSessionPrincipalParams) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipal, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionPrincipalRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, password_hash, role FROM app_user WHERE username = $1
`

type GetUserForLoginRow struct {
	ID           pgtype.UUID
	PasswordHash []byte
	Role         string
}

func (q *Queries) GetUserForLogin(ctx context.Context, username string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, username)
	var i GetUserForLoginRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Role)
	return i, err
}

const listPersistedCollectionTaskStates = `-- name: ListPersistedCollectionTaskStates :many
SELECT task.task_id, task.last_due_at, task.last_started_at, task.last_finished_at, task.last_success_at,
       task.last_result, task.consecutive_failures,
       CASE
           WHEN task.next_eligible_at IS NULL THEN connection.next_eligible_at
           WHEN connection.next_eligible_at IS NULL THEN task.next_eligible_at
           ELSE GREATEST(task.next_eligible_at, connection.next_eligible_at)
       END::timestamptz AS next_eligible_at,
       task.last_error_code, task.last_error_message
FROM instance_collection_task_state task
LEFT JOIN instance_collection_connection_state connection ON connection.instance_id = task.instance_id
WHERE task.instance_id = $1
ORDER BY task.task_id
`

type ListPersistedCollectionTaskStatesRow struct {
	TaskID              string
	LastDueAt           pgtype.Timestamptz
	LastStartedAt       pgtype.Timestamptz
	LastFinishedAt      pgtype.Timestamptz
	LastSuccessAt       pgtype.Timestamptz
	LastResult          pgtype.Text
	ConsecutiveFailures int32
	NextEligibleAt      pgtype.Timestamptz
	LastErrorCode       pgtype.Text
	LastErrorMessage    pgtype.Text
}

func (q *Queries) ListPersistedCollectionTaskStates(ctx context.Context, instanceID pgtype.UUID) ([]ListPersistedCollectionTaskStatesRow, error) {
	rows, err := q.db.Query(ctx, listPersistedCollectionTaskStates, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersistedCollectionTaskStatesRow
	for rows.Next() {
		var i ListPersistedCollectionTaskStatesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LastDueAt,
			&i.LastStartedAt,
			&i.LastFinishedAt,
			&i.LastSuccessAt,
			&i.LastResult,
			&i.ConsecutiveFailures,
			&i.NextEligibleAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
