//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AgentTokenScopes = "agentToken.Scopes"
)

// Defines values for AgentReportMetricsMetric.
const (
	AgentReportMetricsMetricHostCpuUsagePercent           AgentReportMetricsMetric = "host.cpu.usage_percent"
	AgentReportMetricsMetricHostDiskFreeBytes             AgentReportMetricsMetric = "host.disk.free_bytes"
	AgentReportMetricsMetricHostDiskIops                  AgentReportMetricsMetric = "host.disk.iops"
	AgentReportMetricsMetricHostDiskThroughputBytesPerSec AgentReportMetricsMetric = "host.disk.throughput_bytes_per_sec"
	AgentReportMetricsMetricHostDiskUsagePercent          AgentReportMetricsMetric = "host.disk.usage_percent"
	AgentReportMetricsMetricHostMemoryUsagePercent        AgentReportMetricsMetric = "host.memory.usage_percent"
	AgentReportMetricsMetricHostNetworkBytesPerSec        AgentReportMetricsMetric = "host.network.bytes_per_sec"
)

// Defines values for AlertStatus.
const (
	FIRING    AlertStatus = "FIRING"
	NODATA    AlertStatus = "NO_DATA"
	OK        AlertStatus = "OK"
	PENDING   AlertStatus = "PENDING"
	RECOVERED AlertStatus = "RECOVERED"
)

// Defines values for CapabilityStatus.
const (
	MISSING       CapabilityStatus = "MISSING"
	NOTAPPLICABLE CapabilityStatus = "NOT_APPLICABLE"
	PRESENT       CapabilityStatus = "PRESENT"
	UNKNOWN       CapabilityStatus = "UNKNOWN"
)

// Defines values for ErrorErrorCode.
const (
	CONFLICT         ErrorErrorCode = "CONFLICT"
	FORBIDDEN        ErrorErrorCode = "FORBIDDEN"
	INTERNAL         ErrorErrorCode = "INTERNAL"
	NOTFOUND         ErrorErrorCode = "NOT_FOUND"
	UNAUTHENTICATED  ErrorErrorCode = "UNAUTHENTICATED"
	VALIDATIONFAILED ErrorErrorCode = "VALIDATION_FAILED"
)

// Defines values for Role.
const (
	ALERTADMIN    Role = "ALERT_ADMIN"
	PLATFORMADMIN Role = "PLATFORM_ADMIN"
	READONLY      Role = "READONLY"
)

// Defines values for Unavailability.
const (
	AGENTOFFLINE       Unavailability = "AGENT_OFFLINE"
	COLLECTIONFAILED   Unavailability = "COLLECTION_FAILED"
	COLLECTIONPAUSED   Unavailability = "COLLECTION_PAUSED"
	COUNTERRESET       Unavailability = "COUNTER_RESET"
	DBUNREACHABLE      Unavailability = "DB_UNREACHABLE"
	EXTENSIONMISSING   Unavailability = "EXTENSION_MISSING"
	FEATUREDISABLED    Unavailability = "FEATURE_DISABLED"
	NODATAINRANGE      Unavailability = "NO_DATA_IN_RANGE"
	NOSAMPLESYET       Unavailability = "NO_SAMPLES_YET"
	NOTAPPLICABLEROLE  Unavailability = "NOT_APPLICABLE_ROLE"
	PERMISSIONDENIED   Unavailability = "PERMISSION_DENIED"
	STALE              Unavailability = "STALE"
	VERSIONUNSUPPORTED Unavailability = "VERSION_UNSUPPORTED"
)

// Defines values for GetMetricSeriesParamsMetric.
const (
	GetMetricSeriesParamsMetricAgentStatus                       GetMetricSeriesParamsMetric = "agent.status"
	GetMetricSeriesParamsMetricCollectorLastSuccessTime          GetMetricSeriesParamsMetric = "collector.last_success_time"
	GetMetricSeriesParamsMetricHostCpuUsagePercent               GetMetricSeriesParamsMetric = "host.cpu.usage_percent"
	GetMetricSeriesParamsMetricHostDiskFreeBytes                 GetMetricSeriesParamsMetric = "host.disk.free_bytes"
	GetMetricSeriesParamsMetricHostDiskIops                      GetMetricSeriesParamsMetric = "host.disk.iops"
	GetMetricSeriesParamsMetricHostDiskThroughputBytesPerSec     GetMetricSeriesParamsMetric = "host.disk.throughput_bytes_per_sec"
	GetMetricSeriesParamsMetricHostDiskUsagePercent              GetMetricSeriesParamsMetric = "host.disk.usage_percent"
	GetMetricSeriesParamsMetricHostMemoryUsagePercent            GetMetricSeriesParamsMetric = "host.memory.usage_percent"
	GetMetricSeriesParamsMetricHostNetworkBytesPerSec            GetMetricSeriesParamsMetric = "host.network.bytes_per_sec"
	GetMetricSeriesParamsMetricPgAvailabilityReachable           GetMetricSeriesParamsMetric = "pg.availability.reachable"
	GetMetricSeriesParamsMetricPgConnectionActive                GetMetricSeriesParamsMetric = "pg.connection.active"
	GetMetricSeriesParamsMetricPgConnectionIdleInTransaction     GetMetricSeriesParamsMetric = "pg.connection.idle_in_transaction"
	GetMetricSeriesParamsMetricPgConnectionTotal                 GetMetricSeriesParamsMetric = "pg.connection.total"
	GetMetricSeriesParamsMetricPgLockWaitingCount                GetMetricSeriesParamsMetric = "pg.lock.waiting_count"
	GetMetricSeriesParamsMetricPgPreparedXactsCount              GetMetricSeriesParamsMetric = "pg.prepared_xacts.count"
	GetMetricSeriesParamsMetricPgProbeLatencyMs                  GetMetricSeriesParamsMetric = "pg.probe.latency_ms"
	GetMetricSeriesParamsMetricPgQueryLongRunningCount           GetMetricSeriesParamsMetric = "pg.query.long_running_count"
	GetMetricSeriesParamsMetricPgReplicationConnectionState      GetMetricSeriesParamsMetric = "pg.replication.connection_state"
	GetMetricSeriesParamsMetricPgReplicationReplayLagMs          GetMetricSeriesParamsMetric = "pg.replication.replay_lag_ms"
	GetMetricSeriesParamsMetricPgReplicationRole                 GetMetricSeriesParamsMetric = "pg.replication.role"
	GetMetricSeriesParamsMetricPgReplicationSlotRetainedWalBytes GetMetricSeriesParamsMetric = "pg.replication_slot.retained_wal_bytes"
	GetMetricSeriesParamsMetricPgReplicationWalLagBytes          GetMetricSeriesParamsMetric = "pg.replication.wal_lag_bytes"
	GetMetricSeriesParamsMetricPgSessionBlockedCount             GetMetricSeriesParamsMetric = "pg.session.blocked_count"
	GetMetricSeriesParamsMetricPgTempBytesPerSec                 GetMetricSeriesParamsMetric = "pg.temp.bytes_per_sec"
	GetMetricSeriesParamsMetricPgTempFilesPerSec                 GetMetricSeriesParamsMetric = "pg.temp.files_per_sec"
	GetMetricSeriesParamsMetricPgTps                             GetMetricSeriesParamsMetric = "pg.tps"
	GetMetricSeriesParamsMetricPgTransactionLongCount            GetMetricSeriesParamsMetric = "pg.transaction.long_count"
	GetMetricSeriesParamsMetricPgTransactionMaxDurationSec       GetMetricSeriesParamsMetric = "pg.transaction.max_duration_sec"
	GetMetricSeriesParamsMetricPgTuplesReadPerSec                GetMetricSeriesParamsMetric = "pg.tuples.read_per_sec"
	GetMetricSeriesParamsMetricPgTuplesWritePerSec               GetMetricSeriesParamsMetric = "pg.tuples.write_per_sec"
	GetMetricSeriesParamsMetricPgXactCommitPerSec                GetMetricSeriesParamsMetric = "pg.xact.commit_per_sec"
	GetMetricSeriesParamsMetricPgXactRollbackPerSec              GetMetricSeriesParamsMetric = "pg.xact.rollback_per_sec"
)

// Defines values for GetMetricSeriesParamsStep.
const (
	Auto GetMetricSeriesParamsStep = "auto"
	N15s GetMetricSeriesParamsStep = "15s"
	N1m  GetMetricSeriesParamsStep = "1m"
	N5m  GetMetricSeriesParamsStep = "5m"
	Raw  GetMetricSeriesParamsStep = "raw"
)

// AgentReport defines model for AgentReport.
type AgentReport struct {
	InstanceId openapi_types.UUID `json:"instance_id"`
	Metrics    []struct {
		Metric AgentReportMetricsMetric `json:"metric"`
		Value  float32                  `json:"value"`
	} `json:"metrics"`
	Timestamp time.Time `json:"timestamp"`
}

// AgentReportMetricsMetric defines model for AgentReport.Metrics.Metric.
type AgentReportMetricsMetric string

// AlertStatus defines model for AlertStatus.
type AlertStatus string

// CapabilityStatus defines model for CapabilityStatus.
type CapabilityStatus string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code        ErrorErrorCode `json:"code"`
		FieldErrors *[]struct {
			Field   string `json:"field"`
			Message string `json:"message"`
		} `json:"field_errors,omitempty"`
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// Instance defines model for Instance.
type Instance struct {
	AlertStatus AlertStatus        `json:"alert_status"`
	Database    string             `json:"database"`
	Host        string             `json:"host"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Port        int                `json:"port"`
	Username    string             `json:"username"`
}

// InstanceCreated defines model for InstanceCreated.
type InstanceCreated struct {
	// AgentToken Returned once when the instance is created.
	AgentToken string   `json:"agent_token"`
	Instance   Instance `json:"instance"`
}

// InstanceInput defines model for InstanceInput.
type InstanceInput struct {
	Database string `json:"database"`
	Host     string `json:"host"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Port     int    `json:"port"`
	Username string `json:"username"`
}

// MetricSeriesResponse defines model for MetricSeriesResponse.
type MetricSeriesResponse struct {
	From    time.Time `json:"from"`
	Metrics []struct {
		Metric string `json:"metric"`
		Series []struct {
			Labels map[string]string `json:"labels"`
			Points [][]*float64      `json:"points"`
		} `json:"series"`
		Unavailability nullable.Nullable[Unavailability] `json:"unavailability"`
		Unit           string                            `json:"unit"`
	} `json:"metrics"`
	Step string    `json:"step"`
	To   time.Time `json:"to"`
}

// PasswordChangeInput defines model for PasswordChangeInput.
type PasswordChangeInput struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// PasswordIssued defines model for PasswordIssued.
type PasswordIssued struct {
	// Password Generated password returned only in this response.
	Password string `json:"password"`
}

// Role defines model for Role.
type Role string

// Unavailability defines model for Unavailability.
type Unavailability string

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Enabled   bool               `json:"enabled"`
	Id        openapi_types.UUID `json:"id"`
	Role      Role               `json:"role"`
	Username  string             `json:"username"`
}

// UserCreateInput defines model for UserCreateInput.
type UserCreateInput struct {
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// UserCreated defines model for UserCreated.
type UserCreated struct {
	// InitialPassword Generated password returned only in this response.
	InitialPassword string `json:"initial_password"`
	User            User   `json:"user"`
}

// UserRoleInput defines model for UserRoleInput.
type UserRoleInput struct {
	Role Role `json:"role"`
}

// UserStatusInput defines model for UserStatusInput.
type UserStatusInput struct {
	Enabled bool `json:"enabled"`
}

// GetMetricSeriesParams defines parameters for GetMetricSeries.
type GetMetricSeriesParams struct {
	Metric []GetMetricSeriesParamsMetric `form:"metric" json:"metric"`
	From   time.Time                     `form:"from" json:"from"`
	To     time.Time                     `form:"to" json:"to"`
	Step   *GetMetricSeriesParamsStep    `form:"step,omitempty" json:"step,omitempty"`
}

// GetMetricSeriesParamsMetric defines parameters for GetMetricSeries.
type GetMetricSeriesParamsMetric string

// GetMetricSeriesParamsStep defines parameters for GetMetricSeries.
type GetMetricSeriesParamsStep string

// CreateSessionJSONBody defines parameters for CreateSession.
type CreateSessionJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ReportAgentMetricsJSONRequestBody defines body for ReportAgentMetrics for application/json ContentType.
type ReportAgentMetricsJSONRequestBody = AgentReport

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = InstanceInput

// UpdateInstanceJSONRequestBody defines body for UpdateInstance for application/json ContentType.
type UpdateInstanceJSONRequestBody = InstanceInput

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody CreateSessionJSONBody

// ChangeOwnPasswordJSONRequestBody defines body for ChangeOwnPassword for application/json ContentType.
type ChangeOwnPasswordJSONRequestBody = PasswordChangeInput

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateInput

// UpdateUserRoleJSONRequestBody defines body for UpdateUserRole for application/json ContentType.
type UpdateUserRoleJSONRequestBody = UserRoleInput

// UpdateUserStatusJSONRequestBody defines body for UpdateUserStatus for application/json ContentType.
type UpdateUserStatusJSONRequestBody = UserStatusInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/agent/v1/report)
	ReportAgentMetrics(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/instances)
	ListInstances(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/instances)
	CreateInstance(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/instances/{id})
	DeleteInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /api/v1/instances/{id})
	GetInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /api/v1/instances/{id})
	UpdateInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /api/v1/instances/{id}/metrics/series)
	GetMetricSeries(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetMetricSeriesParams)

	// (POST /api/v1/login)
	CreateSession(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)

	// (PUT /api/v1/password)
	ChangeOwnPassword(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/users)
	CreateUser(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/users/{id}/password)
	ResetUserPassword(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /api/v1/users/{id}/role)
	UpdateUserRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /api/v1/users/{id}/status)
	UpdateUserStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ReportAgentMetrics operation middleware
func (siw *ServerInterfaceWrapper) ReportAgentMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportAgentMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateInstance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInstance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateInstance operation middleware
func (siw *ServerInterfaceWrapper) UpdateInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetricSeries operation middleware
func (siw *ServerInterfaceWrapper) GetMetricSeries(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMetricSeriesParams

	// ------------- Required query parameter "metric" -------------

	if paramValue := r.URL.Query().Get("metric"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "metric"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "metric", r.URL.Query(), &params.Metric)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		return
	}

	// ------------- Required query parameter "from" -------------

	if paramValue := r.URL.Query().Get("from"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := r.URL.Query().Get("to"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "step" -------------

	err = runtime.BindQueryParameter("form", true, false, "step", r.URL.Query(), &params.Step)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "step", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetricSeries(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeOwnPassword operation middleware
func (siw *ServerInterfaceWrapper) ChangeOwnPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeOwnPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetUserPassword(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/agent/v1/report", wrapper.ReportAgentMetrics)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/instances", wrapper.ListInstances)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/instances", wrapper.CreateInstance)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/instances/{id}", wrapper.DeleteInstance)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/instances/{id}", wrapper.GetInstance)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/instances/{id}", wrapper.UpdateInstance)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/instances/{id}/metrics/series", wrapper.GetMetricSeries)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/login", wrapper.CreateSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/me", wrapper.GetCurrentUser)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/password", wrapper.ChangeOwnPassword)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/users", wrapper.CreateUser)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/users/{id}/password", wrapper.ResetUserPassword)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/users/{id}/role", wrapper.UpdateUserRole)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/users/{id}/status", wrapper.UpdateUserStatus)

	return m
}

type ReportAgentMetricsRequestObject struct {
	Body *ReportAgentMetricsJSONRequestBody
}

type ReportAgentMetricsResponseObject interface {
	VisitReportAgentMetricsResponse(w http.ResponseWriter) error
}

type ReportAgentMetrics204Response struct {
}

func (response ReportAgentMetrics204Response) VisitReportAgentMetricsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ReportAgentMetrics400JSONResponse Error

func (response ReportAgentMetrics400JSONResponse) VisitReportAgentMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReportAgentMetrics401JSONResponse Error

func (response ReportAgentMetrics401JSONResponse) VisitReportAgentMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListInstancesRequestObject struct {
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []Instance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateInstanceRequestObject struct {
	Body *CreateInstanceJSONRequestBody
}

type CreateInstanceResponseObject interface {
	VisitCreateInstanceResponse(w http.ResponseWriter) error
}

type CreateInstance201JSONResponse InstanceCreated

func (response CreateInstance201JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteInstanceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteInstanceResponseObject interface {
	VisitDeleteInstanceResponse(w http.ResponseWriter) error
}

type DeleteInstance204Response struct {
}

func (response DeleteInstance204Response) VisitDeleteInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetInstanceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetInstanceResponseObject interface {
	VisitGetInstanceResponse(w http.ResponseWriter) error
}

type GetInstance200JSONResponse Instance

func (response GetInstance200JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateInstanceRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateInstanceJSONRequestBody
}

type UpdateInstanceResponseObject interface {
	VisitUpdateInstanceResponse(w http.ResponseWriter) error
}

type UpdateInstance200JSONResponse Instance

func (response UpdateInstance200JSONResponse) VisitUpdateInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricSeriesRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetMetricSeriesParams
}

type GetMetricSeriesResponseObject interface {
	VisitGetMetricSeriesResponse(w http.ResponseWriter) error
}

type GetMetricSeries200JSONResponse MetricSeriesResponse

func (response GetMetricSeries200JSONResponse) VisitGetMetricSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricSeries400JSONResponse Error

func (response GetMetricSeries400JSONResponse) VisitGetMetricSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession204ResponseHeaders struct {
	SetCookie string
}

type CreateSession204Response struct {
	Headers CreateSession204ResponseHeaders
}

func (response CreateSession204Response) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type CreateSession401JSONResponse Error

func (response CreateSession401JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangeOwnPasswordRequestObject struct {
	Body *ChangeOwnPasswordJSONRequestBody
}

type ChangeOwnPasswordResponseObject interface {
	VisitChangeOwnPasswordResponse(w http.ResponseWriter) error
}

type ChangeOwnPassword204Response struct {
}

func (response ChangeOwnPassword204Response) VisitChangeOwnPasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ChangeOwnPassword400JSONResponse Error

func (response ChangeOwnPassword400JSONResponse) VisitChangeOwnPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse []User

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse UserCreated

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse Error

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResetUserPasswordRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ResetUserPasswordResponseObject interface {
	VisitResetUserPasswordResponse(w http.ResponseWriter) error
}

type ResetUserPassword200JSONResponse PasswordIssued

func (response ResetUserPassword200JSONResponse) VisitResetUserPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResetUserPassword400JSONResponse Error

func (response ResetUserPassword400JSONResponse) VisitResetUserPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ResetUserPassword404JSONResponse Error

func (response ResetUserPassword404JSONResponse) VisitResetUserPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserRoleRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateUserRoleJSONRequestBody
}

type UpdateUserRoleResponseObject interface {
	VisitUpdateUserRoleResponse(w http.ResponseWriter) error
}

type UpdateUserRole200JSONResponse User

func (response UpdateUserRole200JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserRole400JSONResponse Error

func (response UpdateUserRole400JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserRole404JSONResponse Error

func (response UpdateUserRole404JSONResponse) VisitUpdateUserRoleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserStatusRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateUserStatusJSONRequestBody
}

type UpdateUserStatusResponseObject interface {
	VisitUpdateUserStatusResponse(w http.ResponseWriter) error
}

type UpdateUserStatus200JSONResponse User

func (response UpdateUserStatus200JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserStatus400JSONResponse Error

func (response UpdateUserStatus400JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserStatus404JSONResponse Error

func (response UpdateUserStatus404JSONResponse) VisitUpdateUserStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/agent/v1/report)
	ReportAgentMetrics(ctx context.Context, request ReportAgentMetricsRequestObject) (ReportAgentMetricsResponseObject, error)

	// (GET /api/v1/instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)

	// (POST /api/v1/instances)
	CreateInstance(ctx context.Context, request CreateInstanceRequestObject) (CreateInstanceResponseObject, error)

	// (DELETE /api/v1/instances/{id})
	DeleteInstance(ctx context.Context, request DeleteInstanceRequestObject) (DeleteInstanceResponseObject, error)

	// (GET /api/v1/instances/{id})
	GetInstance(ctx context.Context, request GetInstanceRequestObject) (GetInstanceResponseObject, error)

	// (PUT /api/v1/instances/{id})
	UpdateInstance(ctx context.Context, request UpdateInstanceRequestObject) (UpdateInstanceResponseObject, error)

	// (GET /api/v1/instances/{id}/metrics/series)
	GetMetricSeries(ctx context.Context, request GetMetricSeriesRequestObject) (GetMetricSeriesResponseObject, error)

	// (POST /api/v1/login)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)

	// (GET /api/v1/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)

	// (PUT /api/v1/password)
	ChangeOwnPassword(ctx context.Context, request ChangeOwnPasswordRequestObject) (ChangeOwnPasswordResponseObject, error)

	// (GET /api/v1/users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)

	// (POST /api/v1/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)

	// (POST /api/v1/users/{id}/password)
	ResetUserPassword(ctx context.Context, request ResetUserPasswordRequestObject) (ResetUserPasswordResponseObject, error)

	// (PUT /api/v1/users/{id}/role)
	UpdateUserRole(ctx context.Context, request UpdateUserRoleRequestObject) (UpdateUserRoleResponseObject, error)

	// (PUT /api/v1/users/{id}/status)
	UpdateUserStatus(ctx context.Context, request UpdateUserStatusRequestObject) (UpdateUserStatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ReportAgentMetrics operation middleware
func (sh *strictHandler) ReportAgentMetrics(w http.ResponseWriter, r *http.Request) {
	var request ReportAgentMetricsRequestObject

	var body ReportAgentMetricsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportAgentMetrics(ctx, request.(ReportAgentMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportAgentMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportAgentMetricsResponseObject); ok {
		if err := validResponse.VisitReportAgentMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(w http.ResponseWriter, r *http.Request) {
	var request ListInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx, request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		if err := validResponse.VisitListInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInstance operation middleware
func (sh *strictHandler) CreateInstance(w http.ResponseWriter, r *http.Request) {
	var request CreateInstanceRequestObject

	var body CreateInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstance(ctx, request.(CreateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInstanceResponseObject); ok {
		if err := validResponse.VisitCreateInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInstance operation middleware
func (sh *strictHandler) DeleteInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteInstanceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInstance(ctx, request.(DeleteInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteInstanceResponseObject); ok {
		if err := validResponse.VisitDeleteInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstance operation middleware
func (sh *strictHandler) GetInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetInstanceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstance(ctx, request.(GetInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstanceResponseObject); ok {
		if err := validResponse.VisitGetInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateInstance operation middleware
func (sh *strictHandler) UpdateInstance(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateInstanceRequestObject

	request.Id = id

	var body UpdateInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInstance(ctx, request.(UpdateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateInstanceResponseObject); ok {
		if err := validResponse.VisitUpdateInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetricSeries operation middleware
func (sh *strictHandler) GetMetricSeries(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetMetricSeriesParams) {
	var request GetMetricSeriesRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetricSeries(ctx, request.(GetMetricSeriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetricSeries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricSeriesResponseObject); ok {
		if err := validResponse.VisitGetMetricSeriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangeOwnPassword operation middleware
func (sh *strictHandler) ChangeOwnPassword(w http.ResponseWriter, r *http.Request) {
	var request ChangeOwnPasswordRequestObject

	var body ChangeOwnPasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangeOwnPassword(ctx, request.(ChangeOwnPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangeOwnPassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangeOwnPasswordResponseObject); ok {
		if err := validResponse.VisitChangeOwnPasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetUserPassword operation middleware
func (sh *strictHandler) ResetUserPassword(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ResetUserPasswordRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetUserPassword(ctx, request.(ResetUserPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetUserPassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetUserPasswordResponseObject); ok {
		if err := validResponse.VisitResetUserPasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUserRole operation middleware
func (sh *strictHandler) UpdateUserRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateUserRoleRequestObject

	request.Id = id

	var body UpdateUserRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserRole(ctx, request.(UpdateUserRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateUserRoleResponseObject); ok {
		if err := validResponse.VisitUpdateUserRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUserStatus operation middleware
func (sh *strictHandler) UpdateUserStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateUserStatusRequestObject

	request.Id = id

	var body UpdateUserStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserStatus(ctx, request.(UpdateUserStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateUserStatusResponseObject); ok {
		if err := validResponse.VisitUpdateUserStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
