// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package instance

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
WITH created AS (
    INSERT INTO instance (id, name, host, port, database_name, username, password_ciphertext, password_key_version, agent_token_hash)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, name, host, port, database_name, username, created_at
), configured AS (
    INSERT INTO instance_collection_config (instance_id)
    SELECT id FROM created
    RETURNING instance_id
)
SELECT created.id, created.name, created.host, created.port, created.database_name, created.username, created.created_at
FROM created
JOIN configured ON configured.instance_id = created.id
`

type CreateInstanceParams struct {
	ID                 pgtype.UUID
	Name               string
	Host               string
	Port               int32
	DatabaseName       string
	Username           string
	PasswordCiphertext []byte
	PasswordKeyVersion int32
	AgentTokenHash     []byte
}

type CreateInstanceRow struct {
	ID           pgtype.UUID
	Name         string
	Host         string
	Port         int32
	DatabaseName string
	Username     string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.PasswordCiphertext,
		arg.PasswordKeyVersion,
		arg.AgentTokenHash,
	)
	var i CreateInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instance WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstance, id)
	return err
}

const getCollectState = `-- name: GetCollectState :one
SELECT last_success_at, last_error_code
FROM instance_collect_state
WHERE instance_id = $1 AND source = 'SERVER_DIRECT'
`

type GetCollectStateRow struct {
	LastSuccessAt pgtype.Timestamptz
	LastErrorCode pgtype.Text
}

func (q *Queries) GetCollectState(ctx context.Context, instanceID pgtype.UUID) (GetCollectStateRow, error) {
	row := q.db.QueryRow(ctx, getCollectState, instanceID)
	var i GetCollectStateRow
	err := row.Scan(&i.LastSuccessAt, &i.LastErrorCode)
	return i, err
}

const getInstance = `-- name: GetInstance :one
SELECT id, name, host, port, database_name, username, agent_token_hash, created_at
FROM instance
WHERE id = $1
`

type GetInstanceRow struct {
	ID             pgtype.UUID
	Name           string
	Host           string
	Port           int32
	DatabaseName   string
	Username       string
	AgentTokenHash []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetInstance(ctx context.Context, id pgtype.UUID) (GetInstanceRow, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i GetInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.AgentTokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionTargets = `-- name: ListCollectionTargets :many
SELECT id, host, port, database_name, username, password_ciphertext, password_key_version, credential_version
FROM instance
ORDER BY id
`

type ListCollectionTargetsRow struct {
	ID                 pgtype.UUID
	Host               string
	Port               int32
	DatabaseName       string
	Username           string
	PasswordCiphertext []byte
	PasswordKeyVersion int32
	CredentialVersion  int64
}

func (q *Queries) ListCollectionTargets(ctx context.Context) ([]ListCollectionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionTargetsRow
	for rows.Next() {
		var i ListCollectionTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.PasswordCiphertext,
			&i.PasswordKeyVersion,
			&i.CredentialVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT id, name, host, port, database_name, username, created_at
FROM instance
ORDER BY name, id
`

type ListInstancesRow struct {
	ID           pgtype.UUID
	Name         string
	Host         string
	Port         int32
	DatabaseName string
	Username     string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListInstances(ctx context.Context) ([]ListInstancesRow, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstancesRow
	for rows.Next() {
		var i ListInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCollectFailure = `-- name: SetCollectFailure :exec
INSERT INTO instance_collect_state (instance_id, source, last_error_code, last_error_message)
VALUES ($1, 'SERVER_DIRECT', $2, $3)
ON CONFLICT (instance_id, source)
DO UPDATE SET last_error_code = EXCLUDED.last_error_code,
              last_error_message = EXCLUDED.last_error_message
`

type SetCollectFailureParams struct {
	InstanceID       pgtype.UUID
	LastErrorCode    pgtype.Text
	LastErrorMessage pgtype.Text
}

func (q *Queries) SetCollectFailure(ctx context.Context, arg SetCollectFailureParams) error {
	_, err := q.db.Exec(ctx, setCollectFailure, arg.InstanceID, arg.LastErrorCode, arg.LastErrorMessage)
	return err
}

const setCollectSuccess = `-- name: SetCollectSuccess :exec
INSERT INTO instance_collect_state (instance_id, source, last_success_at)
VALUES ($1, 'SERVER_DIRECT', $2)
ON CONFLICT (instance_id, source)
DO UPDATE SET last_success_at = EXCLUDED.last_success_at,
              last_error_code = NULL,
              last_error_message = NULL
`

type SetCollectSuccessParams struct {
	InstanceID    pgtype.UUID
	LastSuccessAt pgtype.Timestamptz
}

func (q *Queries) SetCollectSuccess(ctx context.Context, arg SetCollectSuccessParams) error {
	_, err := q.db.Exec(ctx, setCollectSuccess, arg.InstanceID, arg.LastSuccessAt)
	return err
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE instance
SET name = $2,
    host = $3,
    port = $4,
    database_name = $5,
    username = $6,
    password_ciphertext = $7,
    password_key_version = $8,
    credential_version = credential_version + 1
WHERE id = $1
RETURNING id, name, host, port, database_name, username, created_at
`

type UpdateInstanceParams struct {
	ID                 pgtype.UUID
	Name               string
	Host               string
	Port               int32
	DatabaseName       string
	Username           string
	PasswordCiphertext []byte
	PasswordKeyVersion int32
}

type UpdateInstanceRow struct {
	ID           pgtype.UUID
	Name         string
	Host         string
	Port         int32
	DatabaseName string
	Username     string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (UpdateInstanceRow, error) {
	row := q.db.QueryRow(ctx, updateInstance,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.PasswordCiphertext,
		arg.PasswordKeyVersion,
	)
	var i UpdateInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
