// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package metric

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bucketedPointsInRange = `-- name: BucketedPointsInRange :many
SELECT date_bin($4::interval, ts, '2000-01-01'::timestamptz)::timestamptz AS ts,
       avg(value)::double precision AS value
FROM metric_sample
WHERE series_id = $1 AND ts >= $2 AND ts <= $3
GROUP BY 1
ORDER BY 1
`

type BucketedPointsInRangeParams struct {
	SeriesID int64
	Ts       pgtype.Timestamptz
	Ts_2     pgtype.Timestamptz
	Bucket   pgtype.Interval
}

type BucketedPointsInRangeRow struct {
	Ts    pgtype.Timestamptz
	Value float64
}

func (q *Queries) BucketedPointsInRange(ctx context.Context, arg BucketedPointsInRangeParams) ([]BucketedPointsInRangeRow, error) {
	rows, err := q.db.Query(ctx, bucketedPointsInRange,
		arg.SeriesID,
		arg.Ts,
		arg.Ts_2,
		arg.Bucket,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BucketedPointsInRangeRow
	for rows.Next() {
		var i BucketedPointsInRangeRow
		if err := rows.Scan(&i.Ts, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionPlan = `-- name: GetCollectionPlan :one
SELECT agent_metrics_enabled
FROM instance_collection_config
WHERE instance_id = $1
`

func (q *Queries) GetCollectionPlan(ctx context.Context, instanceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCollectionPlan, instanceID)
	var agent_metrics_enabled bool
	err := row.Scan(&agent_metrics_enabled)
	return agent_metrics_enabled, err
}

const latestPoints = `-- name: LatestPoints :many
SELECT ts, value
FROM metric_sample
WHERE series_id = $1 AND ts > $2
ORDER BY ts DESC
LIMIT $3
`

type LatestPointsParams struct {
	SeriesID int64
	Ts       pgtype.Timestamptz
	Limit    int32
}

type LatestPointsRow struct {
	Ts    pgtype.Timestamptz
	Value float64
}

func (q *Queries) LatestPoints(ctx context.Context, arg LatestPointsParams) ([]LatestPointsRow, error) {
	rows, err := q.db.Query(ctx, latestPoints, arg.SeriesID, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPointsRow
	for rows.Next() {
		var i LatestPointsRow
		if err := rows.Scan(&i.Ts, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskIntervals = `-- name: ListTaskIntervals :many
SELECT task_id, interval_seconds
FROM collection_task_config
WHERE instance_id = $1
ORDER BY task_id
`

type ListTaskIntervalsRow struct {
	TaskID          string
	IntervalSeconds int32
}

func (q *Queries) ListTaskIntervals(ctx context.Context, instanceID pgtype.UUID) ([]ListTaskIntervalsRow, error) {
	rows, err := q.db.Query(ctx, listTaskIntervals, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskIntervalsRow
	for rows.Next() {
		var i ListTaskIntervalsRow
		if err := rows.Scan(&i.TaskID, &i.IntervalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pointsInRange = `-- name: PointsInRange :many
SELECT ts, value
FROM metric_sample
WHERE series_id = $1 AND ts >= $2 AND ts <= $3
ORDER BY ts
`

type PointsInRangeParams struct {
	SeriesID int64
	Ts       pgtype.Timestamptz
	Ts_2     pgtype.Timestamptz
}

type PointsInRangeRow struct {
	Ts    pgtype.Timestamptz
	Value float64
}

func (q *Queries) PointsInRange(ctx context.Context, arg PointsInRangeParams) ([]PointsInRangeRow, error) {
	rows, err := q.db.Query(ctx, pointsInRange, arg.SeriesID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointsInRangeRow
	for rows.Next() {
		var i PointsInRangeRow
		if err := rows.Scan(&i.Ts, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesForMetric = `-- name: SeriesForMetric :many
SELECT series_id, labels
FROM metric_series
WHERE instance_id = $1 AND metric_id = $2
ORDER BY series_id
`

type SeriesForMetricParams struct {
	InstanceID pgtype.UUID
	MetricID   string
}

type SeriesForMetricRow struct {
	SeriesID int64
	Labels   []byte
}

func (q *Queries) SeriesForMetric(ctx context.Context, arg SeriesForMetricParams) ([]SeriesForMetricRow, error) {
	rows, err := q.db.Query(ctx, seriesForMetric, arg.InstanceID, arg.MetricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesForMetricRow
	for rows.Next() {
		var i SeriesForMetricRow
		if err := rows.Scan(&i.SeriesID, &i.Labels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentMetricsEnabled = `-- name: SetAgentMetricsEnabled :exec
INSERT INTO instance_collection_config (instance_id, agent_metrics_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (instance_id)
DO UPDATE SET agent_metrics_enabled = EXCLUDED.agent_metrics_enabled,
              updated_at = EXCLUDED.updated_at
`

type SetAgentMetricsEnabledParams struct {
	InstanceID          pgtype.UUID
	AgentMetricsEnabled bool
}

func (q *Queries) SetAgentMetricsEnabled(ctx context.Context, arg SetAgentMetricsEnabledParams) error {
	_, err := q.db.Exec(ctx, setAgentMetricsEnabled, arg.InstanceID, arg.AgentMetricsEnabled)
	return err
}

const setTaskInterval = `-- name: SetTaskInterval :exec
INSERT INTO collection_task_config (instance_id, task_id, interval_seconds, updated_by, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (instance_id, task_id)
DO UPDATE SET interval_seconds = EXCLUDED.interval_seconds,
              updated_by = EXCLUDED.updated_by,
              updated_at = EXCLUDED.updated_at
`

type SetTaskIntervalParams struct {
	InstanceID      pgtype.UUID
	TaskID          string
	IntervalSeconds int32
	UpdatedBy       pgtype.UUID
}

func (q *Queries) SetTaskInterval(ctx context.Context, arg SetTaskIntervalParams) error {
	_, err := q.db.Exec(ctx, setTaskInterval,
		arg.InstanceID,
		arg.TaskID,
		arg.IntervalSeconds,
		arg.UpdatedBy,
	)
	return err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO metric_series (instance_id, metric_id, labels, labels_key, last_seen)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (instance_id, metric_id, labels_key)
DO UPDATE SET last_seen = EXCLUDED.last_seen
RETURNING series_id
`

type UpsertSeriesParams struct {
	InstanceID pgtype.UUID
	MetricID   string
	Labels     []byte
	LabelsKey  string
	LastSeen   pgtype.Timestamptz
}

func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSeries,
		arg.InstanceID,
		arg.MetricID,
		arg.Labels,
		arg.LabelsKey,
		arg.LastSeen,
	)
	var series_id int64
	err := row.Scan(&series_id)
	return series_id, err
}
