package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/liumingjian/dbs-monitor/internal/metric"
)

const appendixPath = "docs/design/01-appendix-implemented.md"

func main() {
	var contents bytes.Buffer
	if err := renderAppendix(&contents); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(appendixPath, contents.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func renderAppendix(destination io.Writer) error {
	var document bytes.Buffer
	document.WriteString("<!-- Code generated by go run ./cmd/metric-appendix; DO NOT EDIT. -->\n")
	document.WriteString("# 指标字典：已实现口径\n\n")
	document.WriteString("本文件由 `internal/metric/dictionary.go` 中的 `Metrics`、`Tasks` 与 `Capabilities` 声明生成。修改 Go 声明后运行 `make gen`，不要手工编辑本文件。\n\n")
	document.WriteString("## 指标索引\n\n")
	document.WriteString("| 指标 | 产生者 | Task | 周期 | 前置条件 | SQL |\n")
	document.WriteString("|---|---|---|---|---|---|\n")
	for _, declaration := range metric.Metrics {
		taskName := "未声明"
		interval := "未声明"
		requirements := "未声明"
		sql := "不适用（非 server SQL Task）"
		if declaration.Producer == metric.ProducerServerTask {
			task, exists := metric.TaskForMetric(declaration.ID)
			if !exists {
				return fmt.Errorf("server metric %s has no declared Task", declaration.ID)
			}
			taskName = "`" + string(task.ID) + "`"
			interval = formatDuration(task.Interval)
			requirements = formatCapabilities(task.Requires)
			sql = "见对应 Task 的 SQL"
		}
		fmt.Fprintf(&document, "| `%s` | `%s` | %s | %s | %s | %s |\n",
			declaration.ID, declaration.Producer, taskName, interval, requirements, sql)
	}

	document.WriteString("\n## Task 声明与 SQL\n")
	for _, task := range metric.Tasks {
		fmt.Fprintf(&document, "\n### Task `%s`\n\n", task.ID)
		fmt.Fprintf(&document, "- 类型：`%s`\n", task.Kind)
		fmt.Fprintf(&document, "- 周期：%s\n", formatDuration(task.Interval))
		fmt.Fprintf(&document, "- 前置条件：%s\n", formatCapabilities(task.Requires))
		fmt.Fprintf(&document, "- 产出指标：%s\n\n", formatYields(task.Yields))
		document.WriteString("```sql\n")
		document.WriteString(strings.TrimSpace(task.SQL))
		document.WriteString("\n```\n")
	}

	_, err := io.Copy(destination, &document)
	return err
}

func formatCapabilities(capabilities []metric.CapabilityID) string {
	if len(capabilities) == 0 {
		return "无"
	}
	values := make([]string, 0, len(capabilities))
	for _, capability := range capabilities {
		values = append(values, "`"+string(capability)+"`")
	}
	return strings.Join(values, "<br>")
}

func formatYields(yields []metric.MetricYield) string {
	if len(yields) == 0 {
		return "不直接产出 `Metrics` 条目"
	}
	values := make([]string, 0, len(yields))
	for _, yield := range yields {
		values = append(values, "`"+yield.Metric.String()+"`")
	}
	return strings.Join(values, "、")
}

func formatDuration(duration time.Duration) string {
	if duration%time.Minute == 0 {
		return fmt.Sprintf("%dm", duration/time.Minute)
	}
	return duration.String()
}
